### ISSUE TITLE
Crash when loading ruby file in VSCode

### ISSUE THREAD

**Issue by theSoenke** [castwide/solargraph#110]
When loading a ruby file in VSCode solargraph crashes since v0.29.0 and v0.29.1 with this error:
```
[NoMethodError] undefined method `scope' for #<Solargraph::Pin::LocalVariable:0x0000559fa4574c40>
```
This seems to be related to the project as I have only been able to reproduce it in one ruby project.

**Comment by castwide** [comment]
I caught this error in v0.29.0 and released a patch in v0.29.1. If you still get the error in 0.29.1, please let me know.

**Comment by theSoenke** [comment]
Here is the full stacktrace:

```
undefined method `scope' for #<Solargraph::Pin::LocalVariable:0x000055ac3ccda418>
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solargraph-0.29.1/lib/solargraph/source_map/node_processor/send_node.rb:139:in `process_private_class_method'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solargraph-0.29.1/lib/solargraph/source_map/node_processor/send_node.rb:26:in `process'
 (at Socket.child.stderr.on (/home/soenke/.vscode/extensions/castwide.solargraph-0.17.6/node_modules/solargraph-utils/out/SocketProvider.js:15:25))

[Extension Host] /home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solargraph-0.29.1/lib/solargraph/source_map/node_processor.rb:70:in `process'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solargraph-0.29.1/lib/solargraph/source_map/node_processor/base.rb:41:in `block in process_children'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solargraph-0.29.1/lib/solargraph/source_map/node_processor/base.rb:39:in `each'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solargraph-0.29.1/lib/solargraph/source_map/node_processor/base.rb:39:in `process_children'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solargraph-0.29.1/lib/solargraph/source_map/node_processor/begin_node.rb:6:in `process'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solargraph-0.29.1/lib/solargraph/source_map/node_processor.rb:70:in `process'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solargraph-0.29.1/lib/solargraph/source_map/node_processor/base.rb:41:in `block in process_children'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solargraph-0.29.1/lib/solargraph/source_map/node_processor/base.rb:39:in `each'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solargraph-0.29.1/lib/solargraph/source_map/node_processor/base.rb:39:in `process_children'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solargraph-0.29.1/lib/solargraph/source_map/node_processor/namespace_node.rb:21:in `process'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solargraph-0.29.1/lib/solargraph/source_map/node_processor.rb:70:in `process'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solargraph-0.29.1/lib/solargraph/source_map/mapper.rb:20:in `map'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solargraph-0.29.1/lib/solargraph/source_map/mapper.rb:38:in `map'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solargraph-0.29.1/lib/solargraph/source_map.rb:134:in `map'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solargraph-0.29.1/lib/solargraph/api_map.rb:83:in `block in catalog'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solargraph-0.29.1/lib/solargraph/api_map.rb:69:in `each'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solargraph-0.29.1/lib/solargraph/api_map.rb:69:in `catalog'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solargraph-0.29.1/lib/solargraph/library.rb:9:in `initialize'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solargraph-0.29.1/lib/solargraph/library.rb:322:in `new'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solargraph-0.29.1/lib/solargraph/library.rb:322:in `load'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solargraph-0.29.1/lib/solargraph/language_server/host.rb:192:in `prepare'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solargraph-0.29.1/lib/solargraph/language_server/message/initialize.rb:8:in `process'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solargraph-0.29.1/lib/solargraph/language_server/host.rb:75:in `start'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solargraph-0.29.1/lib/solargraph/language_server/transport/socket.rb:19:in `process'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solargraph-0.29.1/lib/solargraph/language_server/transport/socket.rb:13:in `block in post_init'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solargraph-0.29.1/lib/solargraph/language_server/transport/data_reader.rb:53:in `parse_message_from_buffer'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solargraph-0.29.1/lib/solargraph/language_server/transport/data_reader.rb:31:in `block in receive'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solargraph-0.29.1/lib/solargraph/language_server/transport/data_reader.rb:26:in `each_char'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solargraph-0.29.1/lib/solargraph/language_server/transport/data_reader.rb:26:in `receive'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solargraph-0.29.1/lib/solargraph/language_server/transport/socket.rb:27:in `receive_data'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solargraph-0.29.1/lib/solargraph/shell.rb:25:in `socket'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
/home/soenke/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/solargraph-0.29.1/bin/solargraph:5:in `<top (required)>'
/home/soenke/.rbenv/versions/2.5.3/bin/solargraph:23:in `load'
/home/soenke/.rbenv/versions/2.5.3/bin/solargraph:23:in `<main>'
 (at Socket.child.stderr.on (/home/soenke/.vscode/extensions/castwide.solargraph-0.17.6/node_modules/solargraph-utils/out/SocketProvider.js:15:25))
```

**Comment by castwide** [comment]
Thanks, @theSoenke. This issue is similar but not directly related to the previous `alias_method` problem. I'll have it fixed in the next patch release.

**Comment by theSoenke** [comment]
That solved it. Thanks!
