### ISSUE TITLE
Exception in 0.30: undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by seagle0128** [castwide/solargraph#131]
Exception in 0.30.0/0.30.1: `undefined method `each' for nil:NilClass`. No issue with 0.29.x. I am running on macOS Mojave.

```elisp
Solargraph is listening on stdio PID=14261
undefined method `each' for nil:NilClass
/usr/local/lib/ruby/gems/2.6.0/gems/solargraph-0.30.1/lib/solargraph/language_server/host.rb:229:in `prepare_folders'
/usr/local/lib/ruby/gems/2.6.0/gems/solargraph-0.30.1/lib/solargraph/language_server/message/initialize.rb:9:in `process'
/usr/local/lib/ruby/gems/2.6.0/gems/solargraph-0.30.1/lib/solargraph/language_server/host.rb:79:in `start'
/usr/local/lib/ruby/gems/2.6.0/gems/solargraph-0.30.1/lib/solargraph/language_server/transport/adapter.rb:17:in `process'
/usr/local/lib/ruby/gems/2.6.0/gems/solargraph-0.30.1/lib/solargraph/language_server/transport/adapter.rb:11:in `block in opening'
/usr/local/lib/ruby/gems/2.6.0/gems/solargraph-0.30.1/lib/solargraph/language_server/transport/data_reader.rb:53:in `parse_message_from_buffer'
/usr/local/lib/ruby/gems/2.6.0/gems/solargraph-0.30.1/lib/solargraph/language_server/transport/data_reader.rb:31:in `block in receive'
/usr/local/lib/ruby/gems/2.6.0/gems/solargraph-0.30.1/lib/solargraph/language_server/transport/data_reader.rb:26:in `each_char'
/usr/local/lib/ruby/gems/2.6.0/gems/solargraph-0.30.1/lib/solargraph/language_server/transport/data_reader.rb:26:in `receive'
/usr/local/lib/ruby/gems/2.6.0/gems/solargraph-0.30.1/lib/solargraph/language_server/transport/adapter.rb:25:in `sending'
/usr/local/lib/ruby/gems/2.6.0/gems/backport-0.2.0/lib/backport/client.rb:32:in `sending'
/usr/local/lib/ruby/gems/2.6.0/gems/backport-0.2.0/lib/backport/server/connectable.rb:7:in `block in tick'
/usr/local/lib/ruby/gems/2.6.0/gems/backport-0.2.0/lib/backport/server/connectable.rb:5:in `each'
/usr/local/lib/ruby/gems/2.6.0/gems/backport-0.2.0/lib/backport/server/connectable.rb:5:in `tick'
/usr/local/lib/ruby/gems/2.6.0/gems/backport-0.2.0/lib/backport/machine.rb:56:in `each'
/usr/local/lib/ruby/gems/2.6.0/gems/backport-0.2.0/lib/backport/machine.rb:56:in `run_server_thread'
/usr/local/lib/ruby/gems/2.6.0/gems/backport-0.2.0/lib/backport/machine.rb:17:in `run'
/usr/local/lib/ruby/gems/2.6.0/gems/backport-0.2.0/lib/backport.rb:49:in `run'
/usr/local/lib/ruby/gems/2.6.0/gems/solargraph-0.30.1/lib/solargraph/shell.rb:39:in `stdio'
/usr/local/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/usr/local/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
/usr/local/lib/ruby/gems/2.6.0/gems/solargraph-0.30.1/bin/solargraph:5:in `<top (required)>'
/usr/local/bin/solargraph:23:in `load'
/usr/local/bin/solargraph:23:in `<main>'
```

**Comment by castwide** [comment]
This looks related to #124. The fix has been merged into the master branch. I expect to release it in gem version 0.30.2 tomorrow.

**Comment by castwide** [comment]
Version 0.30.2 is published.

**Comment by seagle0128** [comment]
I can confirm it has been fixed. Thank you!
