### ISSUE TITLE
undefined method error when hovering in vscode using Rails

### ISSUE THREAD

**Issue by se-ryan** [castwide/solargraph#206]
I get the following error message when I hover over anything (even a blank line) in vscode:

```Request textDocument/hover failed.
  Message: [NoMethodError] undefined method `location' for nil:NilClass
  Code: -32603 
```

![Screen Shot 2019-07-01 at 10 43 02 PM](https://user-images.githubusercontent.com/41924478/60485552-3e6b9500-9c52-11e9-98a8-fa75835db974.jpg)

I've tried following the instructions [here](https://github.com/castwide/solargraph/issues/87) hoping it would help with the issue, but there is no change in the error.

**Comment by castwide** [comment]
Do you get any more detailed messages or a stack trace in the developer console (Help -> Toggle Developer Tools)?

**Comment by se-ryan** [comment]
Interesting items from the console upon hovering:

```
workbench.main.js:238 [Extension Host] [WARN] Error processing request: [NoMethodError] undefined method `location' for nil:NilClass
```
```
workbench.main.js:238 [Extension Host] [WARN] /Users/Ryan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/solargraph-0.34.1/lib/solargraph/source_map/clip.rb:87:in `locals'
/Users/Ryan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/solargraph-0.34.1/lib/solargraph/source_map/clip.rb:19:in `define'
/Users/Ryan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/solargraph-0.34.1/lib/solargraph/library.rb:174:in `definitions_at'
/Users/Ryan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/solargraph-0.34.1/lib/solargraph/language_server/host.rb:496:in `definitions_at'
/Users/Ryan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/solargraph-0.34.1/lib/solargraph/language_server/message/text_document/hover.rb:15:in `process'
/Users/Ryan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/solargraph-0.34.1/lib/solargraph/language_server/host.rb:99:in `receive'
/Users/Ryan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/solargraph-0.34.1/lib/solargraph/language_server/transport/adapter.rb:47:in `process'
/Users/Ryan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/solargraph-0.34.1/lib/solargraph/language_server/transport/adapter.rb:17:in `block in opening'
/Users/Ryan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/solargraph-0.34.1/lib/solargraph/language_server/transport/data_reader.rb:55:in `call'
/Users/Ryan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/solargraph-0.34.1/lib/solargraph/language_server/transport/data_reader.rb:55:in `parse_message_from_buffer'
/Users/Ryan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/solargraph-0.34.1/lib/solargraph/language_server/transport/data_reader.rb:33:in `block in receive'
/Users/Ryan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/solargraph-0.34.1/lib/solargraph/language_server/transport/data_reader.rb:28:in `each_char'
/Users/Ryan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/solargraph-0.34.1/lib/solargraph/language_server/transport/data_reader.rb:28:in `receive'
/Users/Ryan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/solargraph-0.34.1/lib/solargraph/language_server/transport/adapter.rb:27:in `receiving'
/Users/Ryan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/backport-1.1.1/lib/backport/client.rb:63:in `tick'
/Users/Ryan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/backport-1.1.1/lib/backport/server/tcpip.rb:76:in `update'
/Users/Ryan/.rbenv/versions/2.2.2/lib/ruby/2.2.0/observer.rb:196:in `block in notify_observers'
/Users/Ryan/.rbenv/versions/2.2.2/lib/ruby/2.2.0/observer.rb:195:in `each'
/Users/Ryan/.rbenv/versions/2.2.2/lib/ruby/2.2.0/observer.rb:195:in `notify_observers'
/Users/Ryan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/backport-1.1.1/lib/backport/client.rb:121:in `read_input'
/Users/Ryan/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/backport-1.1.1/lib/backport/client.rb:102:in `block in run_input_thread'
```
```
workbench.main.js:238 [Extension Host] rejected promise not handled within 1 second: TypeError: Cannot read property 'contents' of null
t.log @ workbench.main.js:238
$logExtensionHostMessage @ workbench.main.js:3215
_doInvokeHandler @ workbench.main.js:3293
_invokeHandler @ workbench.main.js:3293
_receiveRequest @ workbench.main.js:3292
_receiveOneMessage @ workbench.main.js:3290
_protocol.onMessage.e @ workbench.main.js:3289
fire @ workbench.main.js:77
a @ workbench.main.js:322
e @ workbench.main.js:322
fire @ workbench.main.js:77
_receiveMessage @ workbench.main.js:331
S._socketDisposables.push._socketReader.onMessage.e @ workbench.main.js:328
fire @ workbench.main.js:77
acceptChunk @ workbench.main.js:325
_register._socket.onData.e @ workbench.main.js:324
t @ workbench.main.js:333
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
```
```
workbench.main.js:238 [Extension Host] stack trace: TypeError: Cannot read property 'contents' of null
	at middleware.provideHover.promise.then (/Users/Ryan/.vscode/extensions/castwide.solargraph-0.19.6/out/src/language-client.js:33:27)
t.log @ workbench.main.js:238
$logExtensionHostMessage @ workbench.main.js:3215
_doInvokeHandler @ workbench.main.js:3293
_invokeHandler @ workbench.main.js:3293
_receiveRequest @ workbench.main.js:3292
_receiveOneMessage @ workbench.main.js:3290
_protocol.onMessage.e @ workbench.main.js:3289
fire @ workbench.main.js:77
a @ workbench.main.js:322
e @ workbench.main.js:322
fire @ workbench.main.js:77
_receiveMessage @ workbench.main.js:331
S._socketDisposables.push._socketReader.onMessage.e @ workbench.main.js:328
fire @ workbench.main.js:77
acceptChunk @ workbench.main.js:325
_register._socket.onData.e @ workbench.main.js:324
t @ workbench.main.js:333
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
```
```
workbench.main.js:3241 [[object Object]]Cannot read property 'contents' of null
$onExtensionRuntimeError @ workbench.main.js:3241
_doInvokeHandler @ workbench.main.js:3293
_invokeHandler @ workbench.main.js:3293
_receiveRequest @ workbench.main.js:3292
_receiveOneMessage @ workbench.main.js:3290
_protocol.onMessage.e @ workbench.main.js:3289
fire @ workbench.main.js:77
a @ workbench.main.js:322
e @ workbench.main.js:322
fire @ workbench.main.js:77
_receiveMessage @ workbench.main.js:331
S._socketDisposables.push._socketReader.onMessage.e @ workbench.main.js:328
fire @ workbench.main.js:77
acceptChunk @ workbench.main.js:325
_register._socket.onData.e @ workbench.main.js:324
t @ workbench.main.js:333
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
```
```
workbench.main.js:3241 TypeError: Cannot read property 'contents' of null
	at middleware.provideHover.promise.then (/Users/Ryan/.vscode/extensions/castwide.solargraph-0.19.6/out/src/language-client.js:33)
$onExtensionRuntimeError @ workbench.main.js:3241
_doInvokeHandler @ workbench.main.js:3293
_invokeHandler @ workbench.main.js:3293
_receiveRequest @ workbench.main.js:3292
_receiveOneMessage @ workbench.main.js:3290
_protocol.onMessage.e @ workbench.main.js:3289
fire @ workbench.main.js:77
a @ workbench.main.js:322
e @ workbench.main.js:322
fire @ workbench.main.js:77
_receiveMessage @ workbench.main.js:331
S._socketDisposables.push._socketReader.onMessage.e @ workbench.main.js:328
fire @ workbench.main.js:77
acceptChunk @ workbench.main.js:325
_register._socket.onData.e @ workbench.main.js:324
t @ workbench.main.js:333
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
```

**Comment by castwide** [comment]
I haven't been able to reproduce this one yet, but I suspect it's related to one of two things:

1. A syntax error in the file you're editing
2. A problem inferring the type of a local variable

Either one would indicate a bug in Solargraph's source maps.

One more thing you can try is running `solargraph scan -v` from your workspace's root directory. If it encounters a problem analyzing your code, it should output the last location it tried to analyze and the resulting error. More information: https://solargraph.org/guides/scanning-workspaces

**Comment by se-ryan** [comment]
I ran `solargraph scan -v` and it completed successfully: Scanned WORKSPACE (6446 pins) in 20.540266000083648 seconds. I just received a vscode update (June) and it seems to have fixed things, I can no longer recreate this issue. Solargraph seems to be working as expected for now.
