### ISSUE TITLE
Direct run solargraph and crash, version 0.37.1

### ISSUE THREAD

**Issue by smoothdvd** [castwide/solargraph#222]
```
Traceback (most recent call last):
        24: from /Users/alexgao/.rbenv/versions/2.6.3/bin/solargraph:23:in `<main>'
        23: from /Users/alexgao/.rbenv/versions/2.6.3/bin/solargraph:23:in `load'
        22: from /Users/alexgao/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/solargraph-0.37.1/bin/solargraph:3:in `<top (required)>'
        21: from /Users/alexgao/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        20: from /Users/alexgao/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        19: from /Users/alexgao/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/solargraph-0.37.1/lib/solargraph.rb:57:in `<top (required)>'
        18: from /Users/alexgao/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        17: from /Users/alexgao/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        16: from /Users/alexgao/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/solargraph-0.37.1/lib/solargraph/yard_map.rb:5:in `<top (required)>'
        15: from /Users/alexgao/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/solargraph-0.37.1/lib/solargraph/yard_map.rb:9:in `<module:Solargraph>'
        14: from /Users/alexgao/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/solargraph-0.37.1/lib/solargraph/yard_map.rb:19:in `<class:YardMap>'
        13: from /Users/alexgao/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/yard-0.9.20/lib/yard/registry.rb:146:in `load!'
        12: from /Users/alexgao/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/yard-0.9.20/lib/yard/registry_store.rb:138:in `load!'
        11: from /Users/alexgao/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/yard-0.9.20/lib/yard/registry_store.rb:127:in `load'
        10: from /Users/alexgao/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/yard-0.9.20/lib/yard/registry_store.rb:253:in `load_yardoc'
         9: from /Users/alexgao/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/yard-0.9.20/lib/yard/registry_store.rb:295:in `load_root'
         8: from /Users/alexgao/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/yard-0.9.20/lib/yard/serializers/yardoc_serializer.rb:104:in `deserialize'
         7: from /Users/alexgao/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/yard-0.9.20/lib/yard/globals.rb:21:in `log'
         6: from /Users/alexgao/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         5: from /Users/alexgao/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         4: from /Users/alexgao/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/yard-0.9.20/lib/yard/logging.rb:3:in `<top (required)>'
         3: from /Users/alexgao/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         2: from /Users/alexgao/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
         1: from /Users/alexgao/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/logger-1.4.0/lib/logger.rb:15:in `<top (required)>'
/Users/alexgao/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/logger-1.4.0/lib/logger.rb:15:in `require_relative': cannot load such file -- /Users/alexgao/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/logger-1.4.0/lib/logger/version (LoadError)
```

**Comment by smoothdvd** [comment]
Upgrade logger gem will fix this.
