### ISSUE TITLE
cannot load such file -- backport

### ISSUE THREAD

**Issue by alphabt** [castwide/solargraph#225]
```console
$ solargraph -v
Traceback (most recent call last):
	7: from /Users/iczman/.rbenv/versions/2.6.3/bin/solargraph:23:in `<main>'
	6: from /Users/iczman/.rbenv/versions/2.6.3/bin/solargraph:23:in `load'
	5: from /Users/iczman/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/solargraph-0.37.2/bin/solargraph:5:in `<top (required)>'
	4: from /Users/iczman/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	3: from /Users/iczman/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	2: from /Users/iczman/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/solargraph-0.37.2/lib/solargraph/shell.rb:4:in `<top (required)>'
	1: from /Users/iczman/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/iczman/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- backport (LoadError)
	8: from /Users/iczman/.rbenv/versions/2.6.3/bin/solargraph:23:in `<main>'
	7: from /Users/iczman/.rbenv/versions/2.6.3/bin/solargraph:23:in `load'
	6: from /Users/iczman/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/solargraph-0.37.2/bin/solargraph:5:in `<top (required)>'
	5: from /Users/iczman/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	4: from /Users/iczman/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	3: from /Users/iczman/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/solargraph-0.37.2/lib/solargraph/shell.rb:4:in `<top (required)>'
	2: from /Users/iczman/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	1: from /Users/iczman/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
/Users/iczman/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require': cannot load such file -- backport (LoadError)

$ gem list | ack solargraph
solargraph (0.37.2)

```

**Comment by castwide** [comment]
Backport is one of Solargraph's dependencies. I'm not sure why it's not available. Does it work if you install it via `gem install backport`?

**Comment by alphabt** [comment]
Yea I `gem uninstall backport && gem install backport` and still the same :(

```console
$ gem list | ack backport
backport (default: 1.1.2)
```

**Comment by castwide** [comment]
Strange. I have no idea what the root cause is, but my next step would be to see if it's an issue with either rbenv or the Gemfile (if you're using one).

**Comment by alphabt** [comment]
Yeah my gut feeling also points to the env being borked. Though not sure what else to try. Gemfile isn't in the context when I repro the issue. I'll play around with rbenv to see if that helps.

**Comment by alphabt** [comment]
I recreated rbenv for Ruby 2.6.3 and reinstalled solargraph. It's working fine now, thanks!
