### ISSUE TITLE
`undefined method `include?' for nil:NilClass` in `#maybe_directives?`

### ISSUE THREAD

**Issue by ojab** [castwide/solargraph#231]
I've tried to use solargraph and it fails with the following:
<details><summary>backtrace</summary>

```
[NoMethodError]: undefined method `include?' for nil:NilClass
/home/ojab/.rvm/gems/ruby-2.5.5/gems/solargraph-0.37.2/lib/solargraph/pin/base.rb:126:in `maybe_directives?'
/home/ojab/.rvm/gems/ruby-2.5.5/gems/solargraph-0.37.2/lib/solargraph/pin/base.rb:292:in `collect_macros'
/home/ojab/.rvm/gems/ruby-2.5.5/gems/solargraph-0.37.2/lib/solargraph/pin/base.rb:112:in `macros'
/home/ojab/.rvm/gems/ruby-2.5.5/gems/solargraph-0.37.2/lib/solargraph/api_map/store.rb:117:in `block in named_macros'
/home/ojab/.rvm/gems/ruby-2.5.5/gems/solargraph-0.37.2/lib/solargraph/api_map/store.rb:116:in `each'
/home/ojab/.rvm/gems/ruby-2.5.5/gems/solargraph-0.37.2/lib/solargraph/api_map/store.rb:116:in `named_macros'
/home/ojab/.rvm/gems/ruby-2.5.5/gems/solargraph-0.37.2/lib/solargraph/api_map.rb:57:in `named_macro'
/home/ojab/.rvm/gems/ruby-2.5.5/gems/solargraph-0.37.2/lib/solargraph/source/chain/call.rb:122:in `block in process_directive'
/home/ojab/.rvm/gems/ruby-2.5.5/gems/solargraph-0.37.2/lib/solargraph/source/chain/call.rb:121:in `each'
/home/ojab/.rvm/gems/ruby-2.5.5/gems/solargraph-0.37.2/lib/solargraph/source/chain/call.rb:121:in `process_directive'
/home/ojab/.rvm/gems/ruby-2.5.5/gems/solargraph-0.37.2/lib/solargraph/source/chain/call.rb:96:in `block in inferred_pins'
/home/ojab/.rvm/gems/ruby-2.5.5/gems/solargraph-0.37.2/lib/solargraph/source/chain/call.rb:44:in `map'
/home/ojab/.rvm/gems/ruby-2.5.5/gems/solargraph-0.37.2/lib/solargraph/source/chain/call.rb:44:in `inferred_pins'
/home/ojab/.rvm/gems/ruby-2.5.5/gems/solargraph-0.37.2/lib/solargraph/source/chain/call.rb:33:in `resolve'
/home/ojab/.rvm/gems/ruby-2.5.5/gems/solargraph-0.37.2/lib/solargraph/source/chain.rb:63:in `define'
/home/ojab/.rvm/gems/ruby-2.5.5/gems/solargraph-0.37.2/lib/solargraph/source/chain.rb:72:in `infer'
/home/ojab/.rvm/gems/ruby-2.5.5/gems/solargraph-0.37.2/lib/solargraph/source_map/clip.rb:76:in `infer'
/home/ojab/.rvm/gems/ruby-2.5.5/gems/solargraph-0.37.2/lib/solargraph/pin/method.rb:113:in `block in infer_from_return_nodes'
/home/ojab/.rvm/gems/ruby-2.5.5/gems/solargraph-0.37.2/lib/solargraph/pin/method.rb:99:in `each'
/home/ojab/.rvm/gems/ruby-2.5.5/gems/solargraph-0.37.2/lib/solargraph/pin/method.rb:99:in `infer_from_return_nodes'
/home/ojab/.rvm/gems/ruby-2.5.5/gems/solargraph-0.37.2/lib/solargraph/pin/method.rb:63:in `probe'
/home/ojab/.rvm/gems/ruby-2.5.5/gems/solargraph-0.37.2/lib/solargraph/shell.rb:170:in `block (2 levels) in scan'
/home/ojab/.rvm/gems/ruby-2.5.5/gems/solargraph-0.37.2/lib/solargraph/shell.rb:166:in `each'
/home/ojab/.rvm/gems/ruby-2.5.5/gems/solargraph-0.37.2/lib/solargraph/shell.rb:166:in `block in scan'
/home/ojab/.rvm/rubies/ruby-2.5.5/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
/home/ojab/.rvm/gems/ruby-2.5.5/gems/solargraph-0.37.2/lib/solargraph/shell.rb:164:in `scan'
/home/ojab/.rvm/gems/ruby-2.5.5/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/home/ojab/.rvm/gems/ruby-2.5.5/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
/home/ojab/.rvm/gems/ruby-2.5.5/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
/home/ojab/.rvm/gems/ruby-2.5.5/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
/home/ojab/.rvm/gems/ruby-2.5.5/gems/solargraph-0.37.2/bin/solargraph:5:in `<top (required)>'
/home/ojab/.rvm/gems/ruby-2.5.5/bin/solargraph:23:in `load'
/home/ojab/.rvm/gems/ruby-2.5.5/bin/solargraph:23:in `<main>'
/home/ojab/.rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `eval'
/home/ojab/.rvm/gems/ruby-2.5.5/bin/ruby_executable_hooks:24:in `<main>'
```
</details>

AFAIU it happens on [that file](https://github.com/Mange/roadie/blob/master/lib/roadie/stylesheet.rb), debugging:
```
From: /home/ojab/.rvm/gems/ruby-2.5.5/gems/solargraph-0.37.2/lib/solargraph/pin/base.rb @ line 126 Solargraph::Pin::Base#maybe_directives?:

    123: def maybe_directives?
    124:   return !@directives.empty? if defined?(@directives)
    125:   binding.pry if comments.nil?
 => 126:   @maybe_directives ||= comments.include?('@!')
    127: end

[1] pry(#<Solargraph::Pin::YardPin::Method>)> self
=> #<Solargraph::Pin::YardPin::Method at #<Solargraph::Location /home/ojab/.rvm/gems/ruby-2.5.5/gems/roadie-3.2.2/lib/roadie/stylesheet.rb, #<Solargraph::Range #<Solargraph::Position 7, 0> to #<Solargraph::Position 7, 0>>>>
[2] pry(#<Solargraph::Pin::YardPin::Method>)> code_object.docstring
=> ""
[3] pry(#<Solargraph::Pin::YardPin::Method>)> code_object.docstring.all
=> nil
[4] pry(#<Solargraph::Pin::YardPin::Method>)>
```

**Comment by ojab** [comment]
So AFAIU it fails on `attr_reader :blocks`

**Comment by ojab** [comment]
Simplified testcase:
```ruby
require 'roadie'

class Xxx
  def xxx
    Roadie::Stylesheet.new
  end
end
```

**Comment by castwide** [comment]
I haven't been able to reproduce this error.

1. Is your version of `stylesheet.rb` different from the one in the GitHub repo?
2. Can you tell me what version of YARD you're using?

Either way, I think you've correctly identified the root cause. If the `comments` attribute gets set from `docstring.all`, it should be converted to an empty string instead of `nil`.

**Comment by ojab** [comment]
During testing to produce clonable testcase I found that it crashes with ruby-2.5.5 & ruby-2.5.6 on one machine, but not with ruby-2.5.7 & ruby-2.6.5 and not on the other machine :|
And the issue is gone on the affected machine after reinstalling ruby, so dunno what it was.

**Comment by ojab** [comment]
And it's back. AFAIU it gets `code_objects` from generated yard documentation, so it depends on generated `.yardoc` and `solargraph scan` is essential for reproducing this.
So git clone https://github.com/ojab/solargraph_test, `solargraph bundle` and then `solargraph scan` will lead to this crash.

**Comment by ojab** [comment]
(yard-0.9.20 here)

**Comment by castwide** [comment]
Thanks. I was able to reproduce the error with your test repo. As suspected, the root cause is `comments` being `nil` when set from `docstring.all`.

A minor problem is the use of the `@attr_reader` tag at the top of `Roadie::Stylesheet`. A better alternative would be to use the `@!attribute` directive:

```
  # @!attribute [r] name
  #   the name of the stylesheet ("stylesheets/main.css", "Admin user styles", etc.). The name of the stylesheet will be visible if any errors occur.
  #   @return [String]
  # @!attribute [r] blocks
  #   @return [Array<StyleBlock>]
```

...but either way, it shouldn't cause a fatal error. I'll have a fix for it in the next release.

**Comment by castwide** [comment]
On further inspection, since the `name` and `blocks` attributes are defined in code, the `@!attribute` directive isn't necessary at all. Shortened example:

```ruby
module Roadie
  class Stylesheet
    # the name of the stylesheet ("stylesheets/main.css", "Admin user styles", etc.). The name of the stylesheet will be visible if any errors occur.
    # @return [String]
    attr_reader :name

    # @return [Array<StyleBlock>]
    attr_reader :blocks
  end
end
```

Again, this shouldn't cause a fatal error either way. I'm just making note of best practices.

**Comment by castwide** [comment]
Version 0.38.0 should fix this issue. Please let me know if it persists.
