### ISSUE TITLE
Solargraph throws an exception on `master` branch but works on latest version

### ISSUE THREAD

**Issue by gencer** [castwide/solargraph#244]
Hi current `master` has a problem. Server seems hang and says "starting" all the time and developer tools shows an exception.

**Error**: uninitialized constant Solargraph::LanguageServer::Transport::DataReader::JSON (NameError)

**Stacktrace**:

```
[Extension Host] 	from D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.37.2/lib/solargraph/language_server/transport/data_reader.rb:56:in `parse_message_from_buffer'
	from D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.37.2/lib/solargraph/language_server/transport/data_reader.rb:33:in `block in receive'
	from D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.37.2/lib/solargraph/language_server/transport/data_reader.rb:28:in `each_char'
	from D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.37.2/lib/solargraph/language_server/transport/data_reader.rb:28:in `receive'
	from D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.37.2/lib/solargraph/language_server/transport/adapter.rb:27:in `receiving'
	from D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/backport-1.1.2/lib/backport/client.rb:63:in `tick'
	from D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/backport-1.1.2/lib/backport/server/tcpip.rb:76:in `update'
	from D:/Ruby26-x64/lib/ruby/2.6.0/observer.rb:197:in `block in notify_observers'
	from D:/Ruby26-x64/lib/ruby/2.6.0/observer.rb:196:in `each'
	from D:/Ruby26-x64/lib/ruby/2.6.0/observer.rb:196:in `notify_observers'
	from D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/backport-1.1.2/lib/backport/client.rb:121:in `read_input'
	from D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/backport-1.1.2/lib/backport/client.rb:102:in `block in run_input_thread'
D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.37.2/lib/solargraph/language_server/transport/data_reader.rb:54:in `parse_message_from_buffer': uninitialized constant Solargraph::LanguageServer::Transport::DataReader::JSON (NameError)
	from D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.37.2/lib/solargraph/language_server/transport/data_reader.rb:33:in `block in receive'
	from D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.37.2/lib/solargraph/language_server/transport/data_reader.rb:28:in `each_char'
	from D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.37.2/lib/solargraph/language_server/transport/data_reader.rb:28:in `receive'
	from D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.37.2/lib/solargraph/language_server/transport/adapter.rb:27:in `receiving'
	from D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/backport-1.1.2/lib/backport/client.rb:63:in `tick'
	from D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/backport-1.1.2/lib/backport/server/tcpip.rb:76:in `update'
	from D:/Ruby26-x64/lib/ruby/2.6.0/observer.rb:197:in `block in notify_observers'
	from D:/Ruby26-x64/lib/ruby/2.6.0/observer.rb:196:in `each'
	from D:/Ruby26-x64/lib/ruby/2.6.0/observer.rb:196:in `notify_observers'
	from D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/backport-1.1.2/lib/backport/client.rb:121:in `read_input'
	from D:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/backport-1.1.2/lib/backport/client.rb:102:in `block in run_input_thread'
```

**Comment by castwide** [comment]
This issue arose while I was optimizing dependency loading a few days ago. I just pushed the fix to the master branch.
