### ISSUE TITLE
Raise Exception for conditional assignment

### ISSUE THREAD

**Issue by SolaWing** [castwide/solargraph#257]
eg:

```
a = if 1
      []
    end
```

get type of a will raise error:
```
[WARN] Error processing request: [NoMethodError] undefined method `expression' for nil:NilClass
[WARN] /Users/wang/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/solargraph-0.35.2/lib/solargraph/pin/base_variable.rb:46:in `block in probe'
/Users/wang/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/solargraph-0.35.2/lib/solargraph/pin/base_variable.rb:45:in `each'
/Users/wang/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/solargraph-0.35.2/lib/solargraph/pin/base_variable.rb:45:in `probe'
/Users/wang/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/solargraph-0.35.2/lib/solargraph/pin/base.rb:196:in `realize'
/Users/wang/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/solargraph-0.35.2/lib/solargraph/library.rb:174:in `block in definitions_at'
/Users/wang/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/solargraph-0.35.2/lib/solargraph/library.rb:174:in `map'
/Users/wang/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/solargraph-0.35.2/lib/solargraph/library.rb:174:in `definitions_at'
/Users/wang/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/solargraph-0.35.2/lib/solargraph/language_server/host.rb:502:in `definitions_at'
/Users/wang/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/solargraph-0.35.2/lib/solargraph/language_server/message/text_document/hover.rb:15:in `process'
/Users/wang/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/solargraph-0.35.2/lib/solargraph/language_server/host.rb:101:in `receive'
/Users/wang/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/solargraph-0.35.2/lib/solargraph/language_server/transport/adapter.rb:47:in `process'
/Users/wang/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/solargraph-0.35.2/lib/solargraph/language_server/transport/adapter.rb:17:in `block in opening'
/Users/wang/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/solargraph-0.35.2/lib/solargraph/language_server/transport/data_reader.rb:55:in `parse_message_from_buffer'
/Users/wang/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/solargraph-0.35.2/lib/solargraph/language_server/transport/data_reader.rb:33:in `block in receive'
/Users/wang/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/solargraph-0.35.2/lib/solargraph/language_server/transport/data_reader.rb:28:in `each_char'
/Users/wang/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/solargraph-0.35.2/lib/solargraph/language_server/transport/data_reader.rb:28:in `receive'
/Users/wang/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/solargraph-0.35.2/lib/solargraph/language_server/transport/adapter.rb:27:in `receiving'
/Users/wang/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/backport-1.1.2/lib/backport/client.rb:63:in `tick'
```

wrap expression in function is ok, eg:
```
def fun
  if 1
    []
  elsif 2
    []
  end
end
c = fun
```
c =~ Array

**Comment by castwide** [comment]
I haven't been able to reproduce this error in VS Code with Solargraph 0.38.1. Here's type inference in the hover for the variable:

![image](https://user-images.githubusercontent.com/3704922/71782926-b756fb00-2fad-11ea-8798-42ef126af840.png)

**Comment by SolaWing** [comment]
sorry, the newest version 0.38.1 does work.

 My dev project have slather requirement, which depends on nokogiri (~> 1.8.2). this locks solargraph in old version when use bundler, cause newest version require nokogiri (~> 1.9, >= 1.9.1).

Can we make solargraph dependencies and project dependencies independent of each other?

**Comment by castwide** [comment]
I've been working on ways to make Solargraph work with project bundles more independently. The current version will make an attempt to generate maps from the project's dependencies instead of system gems, even if you start Solargraph without Bundler. It's better than it used to be, but far from perfect; using Bundler is still likely to give you better results.
