### ISSUE TITLE
Scan does not follow symlinks

### ISSUE THREAD

**Issue by Fibrasek** [castwide/solargraph#282]
When running `solargraph scan` on a project, it fails with the following message:
```
[INFO] Indexing workspace files in /home/fibrasek/Dev/<redacted>
/home/fibrasek/.rvm/gems/ruby-2.3.5/gems/solargraph-0.34.1/lib/solargraph/source.rb:491:in `initialize': No such file or directory @ rb_sysopen - /home/fibrasek/Dev/<redacted>/spec/dummy/config/initializers/secure_headers.rb (Errno::ENOENT)
        from /home/fibrasek/.rvm/gems/ruby-2.3.5/gems/solargraph-0.34.1/lib/solargraph/source.rb:491:in `open'
        from /home/fibrasek/.rvm/gems/ruby-2.3.5/gems/solargraph-0.34.1/lib/solargraph/source.rb:491:in `load'
        from /home/fibrasek/.rvm/gems/ruby-2.3.5/gems/solargraph-0.34.1/lib/solargraph/workspace.rb:145:in `block in load_sources'
        from /home/fibrasek/.rvm/gems/ruby-2.3.5/gems/solargraph-0.34.1/lib/solargraph/workspace.rb:144:in `each'
        from /home/fibrasek/.rvm/gems/ruby-2.3.5/gems/solargraph-0.34.1/lib/solargraph/workspace.rb:144:in `load_sources'
        from /home/fibrasek/.rvm/gems/ruby-2.3.5/gems/solargraph-0.34.1/lib/solargraph/workspace.rb:19:in `initialize'
        from /home/fibrasek/.rvm/gems/ruby-2.3.5/gems/solargraph-0.34.1/lib/solargraph/api_map.rb:168:in `new'
        from /home/fibrasek/.rvm/gems/ruby-2.3.5/gems/solargraph-0.34.1/lib/solargraph/api_map.rb:168:in `load'
        from /home/fibrasek/.rvm/gems/ruby-2.3.5/gems/solargraph-0.34.1/lib/solargraph/shell.rb:165:in `block in scan'
        from /home/fibrasek/.rvm/rubies/ruby-2.3.5/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
        from /home/fibrasek/.rvm/gems/ruby-2.3.5/gems/solargraph-0.34.1/lib/solargraph/shell.rb:164:in `scan'
        from /home/fibrasek/.rvm/gems/ruby-2.3.5/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        from /home/fibrasek/.rvm/gems/ruby-2.3.5/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/fibrasek/.rvm/gems/ruby-2.3.5/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        from /home/fibrasek/.rvm/gems/ruby-2.3.5/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        from /home/fibrasek/.rvm/gems/ruby-2.3.5/gems/solargraph-0.34.1/bin/solargraph:5:in `<top (required)>'
        from /home/fibrasek/.rvm/gems/ruby-2.3.5/bin/solargraph:23:in `load'
        from /home/fibrasek/.rvm/gems/ruby-2.3.5/bin/solargraph:23:in `<main>'
        from /home/fibrasek/.rvm/gems/ruby-2.3.5/bin/ruby_executable_hooks:24:in `eval'
        from /home/fibrasek/.rvm/gems/ruby-2.3.5/bin/ruby_executable_hooks:24:in `<main>'
```

When I get into that path and run a `ls -la` it outputs the following:
```
❯ ls -la
total 32
drwxr-xr-x 2 fibrasek fibrasek 4096 nov 19 14:43 ./
drwxr-xr-x 5 fibrasek fibrasek 4096 nov 19 14:43 ../
...
lrwxrwxrwx 1 fibrasek fibrasek   58 nov 19 14:43 secure_headers.rb -> ../../../../../../../config/initializers/secure_headers.rb
...
```

I'm using `Ruby 2.3.5` and `Solargraph 0.34.1` on linux

**Comment by castwide** [comment]
Sorry for the late reply. A similar issue arose in #308 that will be fixed in the next release.

In your case, does the `secure_headers.rb` file exist or is it a dead link? If it exists, that's a different problem I'll need to address.
