### ISSUE TITLE
solargraph -v fails: couldn't find specific bundler version

### ISSUE THREAD

**Issue by abaird** [castwide/solargraph#284]
Solargraph kept failing to install in VSCode, so I went to the command line to investigate:
```
% solargraph -v
Traceback (most recent call last):
	8: from /Users/abaird/.rbenv/versions/2.5.1/bin/solargraph:23:in `<main>'
	7: from /Users/abaird/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems.rb:309:in `activate_bin_path'
	6: from /Users/abaird/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems.rb:309:in `synchronize'
	5: from /Users/abaird/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems.rb:310:in `block in activate_bin_path'
	4: from /Users/abaird/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/specification.rb:1440:in `activate'
	3: from /Users/abaird/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `activate_dependencies'
	2: from /Users/abaird/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/specification.rb:1458:in `each'
	1: from /Users/abaird/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/specification.rb:1469:in `block in activate_dependencies'
/Users/abaird/.rbenv/versions/2.5.1/lib/ruby/2.5.0/rubygems/dependency.rb:312:in `to_specs': Could not find 'bundler' (1.16.6) required by your /Users/abaird/projects/<redacted-path>/Gemfile.lock. (Gem::MissingSpecVersionError)
To update to the lastest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.16.6`
Checked in 'GEM_PATH=/Users/abaird/.gem/ruby/2.5.0:/Users/abaird/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0', execute `gem env` for more information
% gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.7.6
  - RUBY VERSION: 2.5.1 (2018-03-29 patchlevel 57) [x86_64-darwin17]
  - INSTALLATION DIRECTORY: /Users/abaird/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0
  - USER INSTALLATION DIRECTORY: /Users/abaird/.gem/ruby/2.5.0
  - RUBY EXECUTABLE: /Users/abaird/.rbenv/versions/2.5.1/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/abaird/.rbenv/versions/2.5.1/bin
  - SPEC CACHE DIRECTORY: /Users/abaird/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/abaird/.rbenv/versions/2.5.1/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-17
  - GEM PATHS:
     - /Users/abaird/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0
     - /Users/abaird/.gem/ruby/2.5.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :sources => ["https://rubygems.org/", "http://<internal gem server>"]
     - "gem" => "--no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
     - http://<internal gem server>
  - SHELL PATH:
     - /Users/abaird/.rbenv/versions/2.5.1/bin
     - /usr/local/Cellar/rbenv/1.1.2/libexec
     - /usr/local/opt/python/libexec/bin
     - /Users/abaird/.yarn/bin
     - /Users/abaird/.config/yarn/global/node_modules/.bin
     - /usr/local/opt/qt@5.5/bin
     - /Users/abaird/.nvm/versions/node/v10.10.0/bin
     - /Users/abaird/bin/scripts
     - .git/safe/../../bin
     - /Users/abaird/.rbenv/shims
     - /Users/abaird/.bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
% ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
% ls -al /Users/abaird/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems | grep bundler
drwxr-xr-x    9 abaird  <group>    288 Feb 18 10:44 bundler-1.16.6
% gem list solargraph
*** LOCAL GEMS ***
solargraph (0.38.5)
```
I don't have solargraph as part of my Gemfile at the moment, but it seems like it should at least be able to execute. As you can see, I do have the correct version of bundler installed that it wants in the Gemfile.lock. There are probably things that I don't understand about how solargraph tries to find bundler but AFAICT it should have everything it needs to at least run. What am I missing?

I notice also (reading https://github.com/castwide/solargraph/issues/178) that solargraph wants bundler version >=17.2. Could that be causing this issue?

**Comment by castwide** [comment]
This issue was most likely caused by the gem's overly permissive Bundler dependency, which was implemented to support legacy versions of Ruby. With the latest gem requiring Ruby 2,4+, it shouldn't be a problem anymore. Please feel free to reopen or start a new issue if the problem persists.
