### ISSUE TITLE
Server initialization failed

### ISSUE THREAD

**Issue by logicallyanime** [castwide/solargraph#348]
Hello, I just recently upgraded to 0.39.13 and now Solargraph wont start. I am running on VSCode v1.47.3, Windows 10 64-bit 
Ruby 2.6.6p146 (2020-03-31 revision 67876).
```
  [Error - 6:36:20 AM] Server initialization failed.
  Message: [NoMethodError] undefined method `children' for :private_constant:Symbol
  Code: -32603 
```

Output from solargraph scan:
```
PS D:\Desktop> solargraph scan
Traceback (most recent call last):
50: from C:/Ruby26-x64/bin/solargraph:23:in `<main>'
49: from C:/Ruby26-x64/bin/solargraph:23:in `load'
48: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/bin/solargraph:5:in `<top (required)>'        
47: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
46: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
45: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'        
44: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
43: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/shell.rb:171:in `scan'
42: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/benchmark-0.1.0/lib/benchmark.rb:293:in `measure'
41: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/shell.rb:172:in `block in scan'
40: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/api_map.rb:170:in `load'
39: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/api_map.rb:67:in `catalog'
38: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/api_map.rb:67:in `each'
37: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/api_map.rb:85:in `block in catalog'
36: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/source_map.rb:156:in `map'
35: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/source_map/mapper.rb:50:in `map'
34: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/source_map/mapper.rb:26:in `map'
33: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/rubyvm/class_methods.rb:29:in `map'
32: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor.rb:38:in `process'
31: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:36:in `process'
30: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:44:in `process_children'
29: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:44:in `each'
28: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:46:in `block in process_children'
27: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor.rb:38:in `process'
26: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/rubyvm/node_processors/namespace_node.rb:33:in `process'
25: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:44:in `process_children'
24: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:44:in `each'
23: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:46:in `block in process_children'
22: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor.rb:38:in `process'
21: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/rubyvm/node_processors/scope_node.rb:9:in `process'
20: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:44:in `process_children'
19: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:44:in `each'
18: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:46:in `block in process_children'
17: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor.rb:38:in `process'
16: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:36:in `process'
14: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:44:in `each'
13: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:46:in `block in process_children'
12: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor.rb:38:in `process'
11: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:36:in `process'
10: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:44:in `process_children'
9: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:44:in `each'
8: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:46:in `block in process_children'
7: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor.rb:38:in `process'
6: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:36:in `process'
5: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:44:in `process_children'
4: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:44:in `each'
3: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:46:in `block in process_children'
2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor.rb:38:in `process'
1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/rubyvm/node_processors/send_node.rb:47:in `process'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/rubyvm/node_processors/send_node.rb:217:in `process_private_constant': undefined method `children' for :private_constant:Symbol (NoMethodError)
```

Output from Console in Developer Tools:
```
[WARN] C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/rubyvm/node_processors/send_node.rb:217:in `process_private_constant'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/rubyvm/node_processors/send_node.rb:47:in `process'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor.rb:38:in `process'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:46:in `block in process_children'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:44:in `each'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:44:in `process_children'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:36:in `process'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor.rb:38:in `process'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:46:in `block in process_children'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:44:in `each'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:44:in `process_children'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:36:in `process'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor.rb:38:in `process'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:46:in `block in process_children'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:44:in `each'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:44:in `process_children'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:36:in `process'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor.rb:38:in `process'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:46:in `block in process_children'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:44:in `each'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:44:in `process_children'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/rubyvm/node_processors/scope_node.rb:9:in `process'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor.rb:38:in `process'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:46:in `block in process_children'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:44:in `each'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:44:in `process_children'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/rubyvm/node_processors/namespace_node.rb:33:in `process'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor.rb:38:in `process'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:46:in `block in process_children'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:44:in `each'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:44:in `process_children'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor/base.rb:36:in `process'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/node_processor.rb:38:in `process'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/parser/rubyvm/class_methods.rb:29:in `map'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/source_map/mapper.rb:26:in `map'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/source_map/mapper.rb:50:in `map'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/source_map.rb:156:in `map'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/api_map.rb:85:in `block in catalog'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/api_map.rb:67:in `each'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/api_map.rb:67:in `catalog'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/library.rb:23:in `initialize'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/library.rb:377:in `new'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/library.rb:377:in `load'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/language_server/host.rb:278:in `prepare'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/language_server/host.rb:295:in `block in prepare_folders'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/language_server/host.rb:294:in `each'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/language_server/host.rb:294:in `prepare_folders'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/language_server/message/initialize.rb:14:in `block in process'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/benchmark-0.1.0/lib/benchmark.rb:293:in `measure'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/language_server/message/initialize.rb:10:in `process'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/language_server/host.rb:101:in `receive'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/language_server/transport/adapter.rb:44:in `process'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/language_server/transport/adapter.rb:17:in `block in opening'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/language_server/transport/data_reader.rb:59:in `parse_message_from_buffer'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/language_server/transport/data_reader.rb:35:in `block in receive'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/language_server/transport/data_reader.rb:30:in `each_char'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/language_server/transport/data_reader.rb:30:in `receive'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/solargraph-0.39.13/lib/solargraph/language_server/transport/adapter.rb:27:in `receiving'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/backport-1.1.2/lib/backport/client.rb:63:in `tick'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/backport-1.1.2/lib/backport/server/tcpip.rb:76:in `update'
C:/Ruby26-x64/lib/ruby/2.6.0/observer.rb:197:in `block in notify_observers'
C:/Ruby26-x64/lib/ruby/2.6.0/observer.rb:196:in `each'
C:/Ruby26-x64/lib/ruby/2.6.0/observer.rb:196:in `notify_observers'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/backport-1.1.2/lib/backport/client.rb:121:in `read_input'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/backport-1.1.2/lib/backport/client.rb:102:in `block in run_input_thread'
[INFO] Sending response to initialize
[DEBUG] Content-Length: 133
```

**Comment by logicallyanime** [comment]
A bit of an update, when I try running both `Solargraph: Check Solargraph gem version` and `Solargraph: Get environment info` from the Command Palette, I get a friendly error saying 
`Command 'Solargraph: Check Solargraph gem version' resulted in an error (Running the contributed command: 'solargraph.checkGemVersion' failed.)`
I have a feeling this is related...

**Comment by logicallyanime** [comment]
Not a Solargraph issue, after re-installation of VSCode there were no errors.
