### ISSUE TITLE
Solargraph 0.40.1 breaks compatibility with rubocop 0.84 (undefined method `join' for Set)

### ISSUE THREAD

**Issue by metalelf0** [castwide/solargraph#402]
I recently upgrade from solargraph 0.40.0 to 0.40.1.

This caused the following gem upgrades:

```
Using ast 2.4.1 (was 2.4.0)
Using benchmark 0.1.1 (was 0.1.0)
Using jaro_winkler 1.5.4 (was 1.5.3)
Using parser 2.7.2.0 (was 2.6.4.1)
Using rubocop 0.84.0 (was 0.78.0)
Using rubocop-performance 1.7.1 (was 1.6.1)
Using rubocop-rails 2.6.0 (was 2.5.2)
Using yard 0.9.26 (was 0.9.25)
Using solargraph 0.40.1 (was 0.40.0)
```

When I try to start my rails server, here is what I get:

```
/Users/metalelf0/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.84.0/lib/rubocop/cop/style/redundant_conditional.rb:57:in `<class:RedundantConditional>': undefined method `join' for #<Set: {:==, :===, :!=, :<=, :>=, :>, :<}> (NoMethodError)
        from /Users/metalelf0/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.84.0/lib/rubocop/cop/style/redundant_conditional.rb:27:in `<module:Style>'
        from /Users/metalelf0/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.84.0/lib/rubocop/cop/style/redundant_conditional.rb:5:in `<module:Cop>'
        from /Users/metalelf0/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.84.0/lib/rubocop/cop/style/redundant_conditional.rb:4:in `<module:RuboCop>'
        from /Users/metalelf0/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/rubocop-0.84.0/lib/rubocop/cop/style/redundant_conditional.rb:3:in `<main>'
```

The issue appears both with and without `.rubocop.yml`. Running rubocop alone works. I'm on ruby 2.2.2p198, rails 5.2.4.4.

Thanks!

**Comment by metalelf0** [comment]
Fixed by doing some dependency juggling. I managed to upgrade rubocop to 1.0 and the issue was gone. Thanks anyway!
