### ISSUE TITLE
Solargraph error while starting

### ISSUE THREAD

**Issue by kirthivaasan22** [castwide/solargraph#421]
It gives an error while running `solargraph bundle`. No such file or directory - bundle (Errno::ENOENT)

`from /usr/local/bin/solargraph:23:in `<main>'
from /usr/local/bin/solargraph:23:in `load'
from /var/lib/gems/2.7.0/gems/solargraph-0.40.4/bin/solargraph:5:in `<top (required)>'
from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
from /var/lib/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
from /var/lib/gems/2.7.0/gems/solargraph-0.40.4/lib/solargraph/shell.rb:194:in `bundle'
from /var/lib/gems/2.7.0/gems/solargraph-0.40.4/lib/solargraph/documentor.rb:26:in `document'
from /var/lib/gems/2.7.0/gems/solargraph-0.40.4/lib/solargraph/documentor.rb:61:in `specs_from_bundle'
from /var/lib/gems/2.7.0/gems/solargraph-0.40.4/lib/solargraph.rb:65:in `with_clean_env'
from /usr/lib/ruby/2.7.0/bundler.rb:381:in `with_unbundled_env'
from /usr/lib/ruby/2.7.0/bundler.rb:677:in `with_env'
from /usr/lib/ruby/2.7.0/bundler.rb:381:in `block in with_unbundled_env'
from /var/lib/gems/2.7.0/gems/solargraph-0.40.4/lib/solargraph/documentor.rb:62:in `block in specs_from_bundle'
from /var/lib/gems/2.7.0/gems/solargraph-0.40.4/lib/solargraph/documentor.rb:62:in `chdir'
from /var/lib/gems/2.7.0/gems/solargraph-0.40.4/lib/solargraph/documentor.rb:67:in `block (2 levels) in specs_from_bundle'
from /usr/lib/ruby/2.7.0/open3.rb:281:in `capture3'
from /usr/lib/ruby/2.7.0/open3.rb:101:in `popen3'
from /usr/lib/ruby/2.7.0/open3.rb:213:in `popen_run'
/usr/lib/ruby/2.7.0/open3.rb:213:in `spawn': No such file or directory - bundle (Errno::ENOENT)`

**Comment by BenHagan** [comment]
Same here.

**Comment by castwide** [comment]
Do you have `bundler` installed? If so, does your workspace have a Gemfile?

**Comment by castwide** [comment]
Closing for inactivity. The typical cause for this issue is not having Bundler installed, or not having the version expected by the current runtime environment. If the problem persists regardless, please feel free to open a new issue.
