### ISSUE TITLE
Solargraph fails on directory whose name ends in .rb

### ISSUE THREAD

**Issue by anastasds** [castwide/solargraph#423]
When scanning my workspace, Solargraph threw an exception when scanning a directory whose name ends in `.rb`:

```
Traceback (most recent call last):
	17: from /Users/anastasstoyanovsky/.rbenv/versions/2.5.7/bin/solargraph:23:in `<main>'
	16: from /Users/anastasstoyanovsky/.rbenv/versions/2.5.7/bin/solargraph:23:in `load'
	15: from /Users/anastasstoyanovsky/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/solargraph-0.40.4/bin/solargraph:5:in `<top (required)>'
	14: from /Users/anastasstoyanovsky/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	13: from /Users/anastasstoyanovsky/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	12: from /Users/anastasstoyanovsky/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	11: from /Users/anastasstoyanovsky/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	10: from /Users/anastasstoyanovsky/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/solargraph-0.40.4/lib/solargraph/shell.rb:172:in `scan'
	 9: from /Users/anastasstoyanovsky/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/benchmark-0.1.1/lib/benchmark.rb:293:in `measure'
	 8: from /Users/anastasstoyanovsky/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/solargraph-0.40.4/lib/solargraph/shell.rb:173:in `block in scan'
	 7: from /Users/anastasstoyanovsky/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/solargraph-0.40.4/lib/solargraph/api_map.rb:175:in `load'
	 6: from /Users/anastasstoyanovsky/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/solargraph-0.40.4/lib/solargraph/api_map.rb:175:in `new'
	 5: from /Users/anastasstoyanovsky/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/solargraph-0.40.4/lib/solargraph/workspace.rb:27:in `initialize'
	 4: from /Users/anastasstoyanovsky/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/solargraph-0.40.4/lib/solargraph/workspace.rb:148:in `load_sources'
	 3: from /Users/anastasstoyanovsky/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/solargraph-0.40.4/lib/solargraph/workspace.rb:148:in `each'
	 2: from /Users/anastasstoyanovsky/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/solargraph-0.40.4/lib/solargraph/workspace.rb:150:in `block in load_sources'
	 1: from /Users/anastasstoyanovsky/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/solargraph-0.40.4/lib/solargraph/source.rb:515:in `load'
/Users/anastasstoyanovsky/.rbenv/versions/2.5.7/lib/ruby/gems/2.5.0/gems/solargraph-0.40.4/lib/solargraph/source.rb:515:in `read': Is a directory @ io_fread - /Users/anastasstoyanovsky/Documents/code/REDACTED/actually_a_directory.rb (Errno::EISDIR)
```

**Comment by castwide** [comment]
Fixed in v0.41.0.
