### ISSUE TITLE
solargraph fails to initialize, a "warning" condition is returned as a fatal error

### ISSUE THREAD

**Issue by siegel** [castwide/solargraph#428]
I'm writing a new LSP client, and testing with solargraph.

In my test setup, the server fails during initialization, perhaps when trying to ingest my project workspace, which consists of a highly heterogeneous mixture of file types. It turns out that in the middle of all that, there's a directory whose name is "Ruby.rb". (It's a naming convention that my product uses to indicate that a directory's contents are relevant to a specific language, been in place for many years.)

When Solargraph encounters this directory while processing my client's `initialize` request, it dutifully logs a warning:
```
[WARN] Error processing request: [Errno::EISDIR] Is a directory @ io_fread - /Users/siegel/svn/trunk/Redacted/DiskImage/PackageComponents/Redacted/Example Package.bbpackage/Contents/Clippings/Ruby.rb
```

However, this "warning" appears to be fatal, because my client gets this error back in response to `initialize`:

```
Error Domain=LSPResponseError Code=-32603 "[Errno::EISDIR] Is a directory @ io_fread - /Users/siegel/svn/trunk/Redacted/DiskImage/PackageComponents/Redacted/Example Package.bbpackage/Contents/Clippings/Ruby.rb" UserInfo={NSLocalizedDescription=[Errno::EISDIR] Is a directory @ io_fread - /Users/siegel/svn/trunk/Redacted/DiskImage/PackageComponents/Redacted/Example Package.bbpackage/Contents/Clippings/Ruby.rb}
```

I realize this may be a *very* fringe condition, but in particular, I think a condition like this should be logged as a warning (and feel free to use `window/logMessage` or `$/logTrace`, that seems like a valid usage of either) and the offending file system item skipped, and initialization allowed to succeed.

Here is the complete log transcript from my client, in case it is useful:

```
2021-04-07 11:31:15.935: Application startup
2021-04-07 11:31:15.935: macOS version: 10.15.7 (19H524)
2021-04-07 11:31:16.313: stderr output from server: Solargraph is listening on stdio PID=48167

2021-04-07 11:31:18.139: stderr output from server: [WARN] Error processing request: [Errno::EISDIR] Is a directory @ io_fread - /Users/siegel/svn/trunk/Redacted/DiskImage/PackageComponents/Redacted/Example Package.bbpackage/Contents/Clippings/Ruby.rb
[WARN] /Users/siegel/.gem/ruby/3.0.0/gems/solargraph-0.40.4/lib/solargraph/source.rb:515:in `read'
/Users/siegel/.gem/ruby/3.0.0/gems/solargraph-0.40.4/lib/solargraph/source.rb:515:in `load'
/Users/siegel/.gem/ruby/3.0.0/gems/solargraph-0.40.4/lib/solargraph/workspace.rb:150:in `block in load_sources'
/Users/siegel/.gem/ruby/3.0.0/gems/solargraph-0.40.4/lib/solargraph/workspace.rb:148:in `each'
/Users/siegel/.gem/ruby/3.0.0/gems/solargraph-0.40.4/lib/solargraph/workspace.rb:148:in `load_sources'
/Users/siegel/.gem/ruby/3.0.0/gems/solargraph-0.40.4/lib/solargraph/workspace.rb:27:in `initialize'
/Users/siegel/.gem/ruby/3.0.0/gems/solargraph-0.40.4/lib/solargraph/library.rb:375:in `new'
/Users/siegel/.gem/ruby/3.0.0/gems/solargraph-0.40.4/lib/solargraph/library.rb:375:in `load'
/Users/siegel/.gem/ruby/3.0.0/gems/solargraph-0.40.4/lib/solargraph/language_server/host.rb:278:in `prepare'
/Users/siegel/.gem/ruby/3.0.0/gems/solargraph-0.40.4/lib/solargraph/language_server/host.rb:295:in `block in prepare_folders'
/Users/siegel/.gem/ruby/3.0.0/gems/solargraph-0.40.4/lib/solargraph/language_server/host.rb:294:in `each'
/Users/siegel/.gem/ruby/3.0.0/gems/solargraph-0.40.4/lib/solargraph/language_server/host.rb:294:in `prepare_folders'
/Users/siegel/.gem/ruby/3.0.0/gems/solargraph-0.40.4/lib/solargraph/language_server/message/initialize.rb:14:in `block in process'
/usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/benchmark.rb:293:in `measure'
/Users/siegel/.gem/ruby/3.0.0/gems/solargraph-0.40.4/lib/solargraph/language_server/message/initialize.rb:10:in `process'
/Users/siegel/.gem/ruby/3.0.0/gems/solargraph-0.40.4/lib/solargraph/language_server/host.rb:101:in `receive'
/Users/siegel/.gem/ruby/3.0.0/gems/solargraph-0.40.4/lib/solargraph/language_server/transport/adapter.rb:44:in `process'
/Users/siegel/.gem/ruby/3.0.0/gems/solargraph-0.40.4/lib/solargraph/language_server/transport/adapter.rb:17:in `block in opening'
/Users/siegel/.gem/ruby/3.0.0/gems/solargraph-0.40.4/lib/solargraph/language_server/transport/data_reader.rb:59:in `parse_message_from_buffer'
/Users/siegel/.gem/ruby/3.0.0/gems/solargraph-0.40.4/lib/solargraph/language_server/transport/data_reader.rb:35:in `block in receive'
/Users/siegel/.gem/ruby/3.0.0/gems/solargraph-0.40.4/lib/solargraph/language_server/transport/data_reader.rb:30:in `each_char'
/Users/siegel/.gem/ruby/3.0.0/gems/solargraph-0.40.4/lib/solargraph/language_server/transport/data_reader.rb:30:in `receive'
/Users/siegel/.gem/ruby/3.0.0/gems/solargraph-0.40.4/lib/solargraph/language_server/transport/adapter.rb:27:in `receiving'
/Users/siegel/.gem/ruby/3.0.0/gems/backport-1.1.2/lib/backport/client.rb:63:in `tick'
/Users/siegel/.gem/ruby/3.0.0/gems/backport-1.1.2/lib/backport/server/stdio.rb:18:in `update'
/usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/observer.rb:222:in `block in notify_observers'
/usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/observer.rb:221:in `each'
/usr/local/Cellar/ruby/3.0.1/lib/ruby/3.0.0/observer.rb:221:in `notify_observers'
/Users/siegel/.gem/ruby/3.0.0/gems/backport-1.1.2/lib/backport/client.rb:121:in `read_input'
/Users/siegel/.gem/ruby/3.0.0/gems/backport-1.1.2/lib/backport/client.rb:102:in `block in run_input_thread'

2021-04-07 11:31:18.139: Error starting LSP server at /usr/local/lib/ruby/gems/3.0.0/bin/solargraph: Error Domain=LSPResponseError Code=-32603 "[Errno::EISDIR] Is a directory @ io_fread - /Users/siegel/svn/trunk/Redacted/DiskImage/PackageComponents/Redacted/Example Package.bbpackage/Contents/Clippings/Ruby.rb" UserInfo={NSLocalizedDescription=[Errno::EISDIR] Is a directory @ io_fread - /Users/siegel/svn/trunk/Redacted/DiskImage/PackageComponents/Redacted/Example Package.bbpackage/Contents/Clippings/Ruby.rb}
```

Please let me know if there are any additional diagnostics or information I can provide.

**Comment by castwide** [comment]
This issue appears to be identical to #423. It should be fixed in gem v0.41.0.
