### ISSUE TITLE
Server cannot handle client response to client/registerCapability

### ISSUE THREAD

**Issue by iftheshoefritz** [castwide/solargraph#446]
When my editor starts solargraph and the first Ruby file opens, the LSP client sends:

```
[Trace - 02:08:10 pm] Sending notification 'textDocument/didOpen'.
Params: {
  "textDocument": {
    "uri": "file:///Users/frederickmeissner/devprojects/solartest/app/models/book.rb",
    "languageId": "ruby",
    "version": 27,
    "text": "# == Schema Information\n#\n# Table name: books\n#\n#  id         :integer          not null, primary key\n#  created_at :datetime         not null\n#  updated_at :datetime         not null\n#  author_id  :integer          not null\n#\n# Indexes\n#\n#  index_books_on_author_id  (author_id)\n#\n# Foreign Keys\n#\n#  author_id  (author_id => authors.id)\n#\nclass Book < ApplicationRecord\n  belongs_to :author\n\n  def other_books_for_same_author\n    author\n  end\nend\n"
  }
}
```

Then the server responds with:

```
[Trace - 02:08:10 pm] Received request 'window/workDoneProgress/create - (0).
Params: {
  "token": "05e971b6-8390-41b0-852a-7d7e40d164ce"
}
```

then the client sends:

```
[Trace - 02:08:10 pm] Sending response 'window/workDoneProgress/create - (0)'. Processing request took 0ms
Params: {
  "jsonrpc": "2.0",
  "id": 0,
  "result": null
}
```

and Solargraph crashes with:

```
#<Thread:0x0000000128ab4018 /Users/frederickmeissner/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/backport-1.1.2/lib/backport/client.rb:101 run> terminated with exception (report_on_exception is true):
/Users/frederickmeissner/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/solargraph-0.41.2/lib/solargraph/language_server/host.rb:111:in `receive': undefined method `process' for nil:NilClass (NoMethodError)
	from /Users/frederickmeissner/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/solargraph-0.41.2/lib/solargraph/language_server/transport/adapter.rb:44:in `process'
	from /Users/frederickmeissner/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/solargraph-0.41.2/lib/solargraph/language_server/transport/adapter.rb:17:in `block in opening'
	from /Users/frederickmeissner/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/solargraph-0.41.2/lib/solargraph/language_server/transport/data_reader.rb:59:in `parse_message_from_buffer'
	from /Users/frederickmeissner/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/solargraph-0.41.2/lib/solargraph/language_server/transport/data_reader.rb:35:in `block in receive'
	from /Users/frederickmeissner/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/solargraph-0.41.2/lib/solargraph/language_server/transport/data_reader.rb:30:in `each_char'
	from /Users/frederickmeissner/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/solargraph-0.41.2/lib/solargraph/language_server/transport/data_reader.rb:30:in `receive'
	from /Users/frederickmeissner/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/solargraph-0.41.2/lib/solargraph/language_server/transport/adapter.rb:27:in `receiving'
	from /Users/frederickmeissner/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/backport-1.1.2/lib/backport/client.rb:63:in `tick'
	from /Users/frederickmeissner/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/backport-1.1.2/lib/backport/server/stdio.rb:18:in `update'
	from /Users/frederickmeissner/.asdf/installs/ruby/3.0.0/lib/ruby/3.0.0/observer.rb:222:in `block in notify_observers'
	from /Users/frederickmeissner/.asdf/installs/ruby/3.0.0/lib/ruby/3.0.0/observer.rb:221:in `each'
	from /Users/frederickmeissner/.asdf/installs/ruby/3.0.0/lib/ruby/3.0.0/observer.rb:221:in `notify_observers'
	from /Users/frederickmeissner/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/backport-1.1.2/lib/backport/client.rb:121:in `read_input'
	from /Users/frederickmeissner/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/backport-1.1.2/lib/backport/client.rb:102:in `block in run_input_thread'
```

This happens on solargraph `0.41.1`, `0.41.2`, `0.42.0`. Admittedly I'm running an experimental version of `solargraph-rails`. I don't see how anything I'm doing would affect things so early in the initialisation though. I see these lines in the solargraph code:

```
          # @todo What if the id is invalid?
          requests[request['id']].process(request['result'])
```

the todo seems to be related.

**Comment by castwide** [comment]
That should be resolved as of 0.42.0 (now 0.42.1 due to an unrelated patch). The code you quoted has been changed to this:

```ruby
          if requests[request['id']]
            requests[request['id']].process(request['result'])
            requests.delete request['id']
          else
            logger.warn "Discarding client response to unrecognized message #{request['id']}"
          end
```

**Comment by iftheshoefritz** [comment]
I upgraded to 0.42.2 and now I have:

```
[WARN] Discarding client response to unrecognized message 0
#<Thread:0x0000000114877430 /Users/frederickmeissner/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/backport-1.1.2/lib/backport/client.rb:101 run> terminated with exception (report_on_exception is true):
/Users/frederickmeissner/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/solargraph-0.42.1/lib/solargraph/language_server/transport/adapter.rb:45:in `process': undefined method `send_response' for true:TrueClass (NoMethodError)
	from /Users/frederickmeissner/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/solargraph-0.42.1/lib/solargraph/language_server/transport/adapter.rb:17:in `block in opening'
	from /Users/frederickmeissner/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/solargraph-0.42.1/lib/solargraph/language_server/transport/data_reader.rb:59:in `parse_message_from_buffer'
	from /Users/frederickmeissner/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/solargraph-0.42.1/lib/solargraph/language_server/transport/data_reader.rb:35:in `block in receive'
	from /Users/frederickmeissner/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/solargraph-0.42.1/lib/solargraph/language_server/transport/data_reader.rb:30:in `each_char'
	from /Users/frederickmeissner/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/solargraph-0.42.1/lib/solargraph/language_server/transport/data_reader.rb:30:in `receive'
	from /Users/frederickmeissner/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/solargraph-0.42.1/lib/solargraph/language_server/transport/adapter.rb:27:in `receiving'
	from /Users/frederickmeissner/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/backport-1.1.2/lib/backport/client.rb:63:in `tick'
	from /Users/frederickmeissner/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/backport-1.1.2/lib/backport/server/stdio.rb:18:in `update'
	from /Users/frederickmeissner/.asdf/installs/ruby/3.0.0/lib/ruby/3.0.0/observer.rb:222:in `block in notify_observers'
	from /Users/frederickmeissner/.asdf/installs/ruby/3.0.0/lib/ruby/3.0.0/observer.rb:221:in `each'
	from /Users/frederickmeissner/.asdf/installs/ruby/3.0.0/lib/ruby/3.0.0/observer.rb:221:in `notify_observers'
	from /Users/frederickmeissner/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/backport-1.1.2/lib/backport/client.rb:121:in `read_input'
	from /Users/frederickmeissner/.asdf/installs/ruby/3.0.0/lib/ruby/gems/3.0.0/gems/backport-1.1.2/lib/backport/client.rb:102:in `block in run_input_thread'
```

**Comment by castwide** [comment]
Do you know what the client's response to `window/workDoneProgress/create` is? The server expects it to be `void` (`nil`) if the request succeeded.

**Comment by castwide** [comment]
Version 0.42.2 fixes two possibly related issues:
* Server request IDs start with 1 instead of 0 in case the client treats 0 as a falsy value.
* The transport adapter gracefully handles responses to unrecognized requests.

**Comment by iftheshoefritz** [comment]
Thanks for the update!

For reference, here are the `workDoneProgress/create` logs:

```
[Trace - 08:57:16 am] Received request 'window/workDoneProgress/create - (0).
Params: {
  "token": "9102f642-8598-431a-a8d9-0a406eb8c822"
}


[Trace - 08:57:16 am] Sending response 'window/workDoneProgress/create - (0)'. Processing request took 0ms
Params: {
  "jsonrpc": "2.0",
  "id": 0,
  "result": null
}
```

**Comment by castwide** [comment]
The request and response look good. I'm guessing the root cause of your problem was the response handling in the transport adapter. Thanks for following up. Let me know if the problem persists.

**Comment by iftheshoefritz** [comment]
Thanks, the server seems much more robust after the upgrade 👍
