### ISSUE TITLE
solargraph sometimes doesn't map workspace on start

### ISSUE THREAD

**Issue by samk1** [castwide/solargraph#461]
Hi

I'm struggling with an issue where solargraph does not map all sources in a workspace upon starting.

I think I've narrowed it down to the async_library_map function of host.rb.

If I set client_supports_progress? to false, I can no longer reproduce the problem, so that might have something to do with it.

I also can't seem to reproduce it when running solargraph from the terminal as an external process instead of within VSCode.

I have tried setting the log level to INFO, and capturing logs when the problem occurs vs. when it does not, the result is below. I also added a few logging statements to try to narrow down the problem a bit more.

```
 #host .rb
      def async_library_map library
        Solargraph.logger.warn("async_library_map library.mapped?: #{library.mapped?}")
        return if library.mapped?
        Thread.new do
          if client_supports_progress?
            uuid = SecureRandom.uuid
            send_request 'window/workDoneProgress/create', {
              token: uuid
            } do |response|
              do_async_library_map library, response.nil? ? uuid : nil
            end
          else
            do_async_library_map library
          end
        end
      end
      
      def do_async_library_map library, uuid = nil
        Solargraph.logger.warn("mapping started")
        total = library.workspace.sources.length
        if uuid
          send_notification '$/progress', {
            token: uuid,
            value: {
              kind: 'begin',
              title: "Mapping workspace",
              message: "0/#{total} files",
              cancellable: false,
              percentage: 0
            }
          }
        end
        pct = 0
        mod = 10
        while library.next_map
          next unless uuid
          cur = ((library.source_map_hash.keys.length.to_f / total.to_f) * 100).to_i
          if cur > pct && cur % mod == 0
            pct = cur
            send_notification '$/progress', {
              token: uuid,
              value: {
                kind: 'report',
                cancellable: false,
                message: "#{library.source_map_hash.keys.length}/#{total} files",
                percentage: pct
              }
            }
          end
        end
        Solargraph.logger.warn("mapping ended")
        if uuid
          send_notification '$/progress', {
            token: uuid,
            value: {
              kind: 'end',
              message: 'Mapping complete'
            }
          }
        end
      end
 ```
 
 When the problem occurs, the dev tools log in VS code shows this:
 
 ```
[Extension Host] [INFO] Server received shutdown
console.ts:137 [Extension Host] [INFO] Sending response to shutdown
console.ts:137 [Extension Host] Solargraph is listening PORT=55740 PID=18657
console.ts:137 [Extension Host] [INFO] Preparing library for /Users/sam/projects/fresho/projects/production-apps/fresho-app
console.ts:137 [Extension Host] [WARN] load_sources
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
m @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:35
_doInvokeHandler @ rpcProtocol.ts:418
_invokeHandler @ rpcProtocol.ts:403
_receiveRequest @ rpcProtocol.ts:319
_receiveOneMessage @ rpcProtocol.ts:246
(anonymous) @ rpcProtocol.ts:111
fire @ event.ts:583
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:866
(anonymous) @ ipc.net.ts:705
fire @ event.ts:583
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
T @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
console.ts:137 [Extension Host] stack trace: Error [ERR_STREAM_WRITE_AFTER_END]: write after end	at Socket.Writable.write (internal/streams/writable.js:292:11)	at /Users/sam/.vscode/extensions/castwide.solargraph-0.23.0/node_modules/vscode-jsonrpc/lib/node/ril.js:90:29	at new Promise (<anonymous>)	at WritableStreamWrapper.write (/Users/sam/.vscode/extensions/castwide.solargraph-0.23.0/node_modules/vscode-jsonrpc/lib/node/ril.js:80:16)	at StreamMessageWriter.doWrite (/Users/sam/.vscode/extensions/castwide.solargraph-0.23.0/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:100:33)	at /Users/sam/.vscode/extensions/castwide.solargraph-0.23.0/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:91:29	at runNextTicks (internal/process/task_queues.js:58:5)	at processImmediate (internal/timers.js:434:9)
m @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:35
_doInvokeHandler @ rpcProtocol.ts:418
_invokeHandler @ rpcProtocol.ts:403
_receiveRequest @ rpcProtocol.ts:319
_receiveOneMessage @ rpcProtocol.ts:246
(anonymous) @ rpcProtocol.ts:111
fire @ event.ts:583
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:866
(anonymous) @ ipc.net.ts:705
fire @ event.ts:583
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
T @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
mainThreadExtensionService.ts:63 [[object Object]]write after end
$onExtensionRuntimeError @ mainThreadExtensionService.ts:63
_doInvokeHandler @ rpcProtocol.ts:418
_invokeHandler @ rpcProtocol.ts:403
_receiveRequest @ rpcProtocol.ts:319
_receiveOneMessage @ rpcProtocol.ts:246
(anonymous) @ rpcProtocol.ts:111
fire @ event.ts:583
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:866
(anonymous) @ ipc.net.ts:705
fire @ event.ts:583
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
T @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
mainThreadExtensionService.ts:64 Error [ERR_STREAM_WRITE_AFTER_END]: write after end
	at Socket.Writable.write (internal/streams/writable.js:292)
	at vscode-file://vscode-app/Users/sam/.vscode/extensions/castwide.solargraph-0.23.0/node_modules/vscode-jsonrpc/lib/node/ril.js:90
	at new Promise (<anonymous>)
	at WritableStreamWrapper.write (vscode-file://vscode-app/Users/sam/.vscode/extensions/castwide.solargraph-0.23.0/node_modules/vscode-jsonrpc/lib/node/ril.js:80)
	at StreamMessageWriter.doWrite (vscode-file://vscode-app/Users/sam/.vscode/extensions/castwide.solargraph-0.23.0/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:100)
	at vscode-file://vscode-app/Users/sam/.vscode/extensions/castwide.solargraph-0.23.0/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:91
	at runNextTicks (internal/process/task_queues.js:58)
	at processImmediate (internal/timers.js:434)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:64
_doInvokeHandler @ rpcProtocol.ts:418
_invokeHandler @ rpcProtocol.ts:403
_receiveRequest @ rpcProtocol.ts:319
_receiveOneMessage @ rpcProtocol.ts:246
(anonymous) @ rpcProtocol.ts:111
fire @ event.ts:583
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:866
(anonymous) @ ipc.net.ts:705
fire @ event.ts:583
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
T @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
console.ts:137 [Extension Host] [INFO] Indexing workspace files in /Users/sam/projects/fresho/projects/production-apps/fresho-app[WARN] included: 3165 excluded: 1
console.ts:137 [Extension Host] [WARN] included: 3165 excluded: 1
console.ts:137 [Extension Host] [WARN] async_library_map library.mapped?: false
console.ts:137 [Extension Host] [INFO] Sending response to initialize
console.ts:137 [Extension Host] [INFO] Server received initialized
console.ts:137 [Extension Host] [INFO] Server sent window/workDoneProgress/create
console.ts:137 [Extension Host] [INFO] Server sent client/registerCapability
console.ts:137 [Extension Host] [INFO] Server received workspace/didChangeConfiguration[INFO] Server received textDocument/didOpen
2console.ts:137 [Extension Host] [INFO] Server received textDocument/didOpen
console.ts:137 [Extension Host] [INFO] Server received $/solargraph/checkGemVersion
console.ts:137 [Extension Host] [INFO] Server received textDocument/documentSymbol
console.ts:137 [Extension Host] [INFO] Loading gems for bundler/require
console.ts:137 [Extension Host] [INFO] Sending response to textDocument/documentSymbol
```

And when it works, the log looks like this:

```
[Extension Host] [INFO] Server received shutdown
console.ts:137 [Extension Host] [INFO] Sending response to shutdown
console.ts:137 [Extension Host] Solargraph is listening PORT=55753 PID=19347
console.ts:137 [Extension Host] [INFO] Preparing library for /Users/sam/projects/fresho/projects/production-apps/fresho-app
console.ts:137 [Extension Host] [WARN] load_sources
console.ts:137 [Extension Host] rejected promise not handled within 1 second: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
m @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:35
_doInvokeHandler @ rpcProtocol.ts:418
_invokeHandler @ rpcProtocol.ts:403
_receiveRequest @ rpcProtocol.ts:319
_receiveOneMessage @ rpcProtocol.ts:246
(anonymous) @ rpcProtocol.ts:111
fire @ event.ts:583
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:866
(anonymous) @ ipc.net.ts:705
fire @ event.ts:583
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
T @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
console.ts:137 [Extension Host] stack trace: Error [ERR_STREAM_WRITE_AFTER_END]: write after end	at Socket.Writable.write (internal/streams/writable.js:292:11)	at /Users/sam/.vscode/extensions/castwide.solargraph-0.23.0/node_modules/vscode-jsonrpc/lib/node/ril.js:90:29	at new Promise (<anonymous>)	at WritableStreamWrapper.write (/Users/sam/.vscode/extensions/castwide.solargraph-0.23.0/node_modules/vscode-jsonrpc/lib/node/ril.js:80:16)	at StreamMessageWriter.doWrite (/Users/sam/.vscode/extensions/castwide.solargraph-0.23.0/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:100:33)	at /Users/sam/.vscode/extensions/castwide.solargraph-0.23.0/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:91:29	at runNextTicks (internal/process/task_queues.js:58:5)	at processImmediate (internal/timers.js:434:9)
m @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:35
_doInvokeHandler @ rpcProtocol.ts:418
_invokeHandler @ rpcProtocol.ts:403
_receiveRequest @ rpcProtocol.ts:319
_receiveOneMessage @ rpcProtocol.ts:246
(anonymous) @ rpcProtocol.ts:111
fire @ event.ts:583
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:866
(anonymous) @ ipc.net.ts:705
fire @ event.ts:583
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
T @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
mainThreadExtensionService.ts:63 [[object Object]]write after end
$onExtensionRuntimeError @ mainThreadExtensionService.ts:63
_doInvokeHandler @ rpcProtocol.ts:418
_invokeHandler @ rpcProtocol.ts:403
_receiveRequest @ rpcProtocol.ts:319
_receiveOneMessage @ rpcProtocol.ts:246
(anonymous) @ rpcProtocol.ts:111
fire @ event.ts:583
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:866
(anonymous) @ ipc.net.ts:705
fire @ event.ts:583
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
T @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
mainThreadExtensionService.ts:64 Error [ERR_STREAM_WRITE_AFTER_END]: write after end
	at Socket.Writable.write (internal/streams/writable.js:292)
	at vscode-file://vscode-app/Users/sam/.vscode/extensions/castwide.solargraph-0.23.0/node_modules/vscode-jsonrpc/lib/node/ril.js:90
	at new Promise (<anonymous>)
	at WritableStreamWrapper.write (vscode-file://vscode-app/Users/sam/.vscode/extensions/castwide.solargraph-0.23.0/node_modules/vscode-jsonrpc/lib/node/ril.js:80)
	at StreamMessageWriter.doWrite (vscode-file://vscode-app/Users/sam/.vscode/extensions/castwide.solargraph-0.23.0/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:100)
	at vscode-file://vscode-app/Users/sam/.vscode/extensions/castwide.solargraph-0.23.0/node_modules/vscode-jsonrpc/lib/common/messageWriter.js:91
	at runNextTicks (internal/process/task_queues.js:58)
	at processImmediate (internal/timers.js:434)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:64
_doInvokeHandler @ rpcProtocol.ts:418
_invokeHandler @ rpcProtocol.ts:403
_receiveRequest @ rpcProtocol.ts:319
_receiveOneMessage @ rpcProtocol.ts:246
(anonymous) @ rpcProtocol.ts:111
fire @ event.ts:583
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:866
(anonymous) @ ipc.net.ts:705
fire @ event.ts:583
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
T @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
console.ts:137 [Extension Host] [INFO] Indexing workspace files in /Users/sam/projects/fresho/projects/production-apps/fresho-app[WARN] included: 3165 excluded: 1
console.ts:137 [Extension Host] [WARN] included: 3165 excluded: 1
console.ts:137 [Extension Host] [WARN] async_library_map library.mapped?: false
console.ts:137 [Extension Host] [INFO] Sending response to initialize
console.ts:137 [Extension Host] [INFO] Server received initialized
console.ts:137 [Extension Host] [INFO] Server sent client/registerCapability
console.ts:137 [Extension Host] [INFO] Server sent window/workDoneProgress/create
console.ts:137 [Extension Host] [INFO] Server received workspace/didChangeConfiguration
3console.ts:137 [Extension Host] [INFO] Server received textDocument/didOpen
console.ts:137 [Extension Host] [INFO] Server received $/solargraph/checkGemVersion
console.ts:137 [Extension Host] [WARN] mapping started
10console.ts:137 [Extension Host] [INFO] Server sent $/progress
console.ts:137 [Extension Host] [INFO] Cataloging /Users/sam/projects/fresho/projects/production-apps/fresho-app
console.ts:137 [Extension Host] [INFO] Server sent $/progress
console.ts:137 [Extension Host] [WARN] mapping ended
console.ts:137 [Extension Host] [INFO] Server sent $/progress
console.ts:137 [Extension Host] [WARN] Discarding client response to unrecognized message 1[INFO] Server received textDocument/documentSymbol
console.ts:137 [Extension Host] [INFO] Loading gems for bundler/require
console.ts:137 [Extension Host] [INFO] Loading net stdlib from cache
console.ts:137 [Extension Host] [INFO] Loading securerandom stdlib from cache
console.ts:137 [Extension Host] [INFO] Loading timeout stdlib from cache
console.ts:137 [Extension Host] [INFO] Loading resolv stdlib from cache
console.ts:137 [Extension Host] [INFO] Loading fileutils stdlib from cache
console.ts:137 [Extension Host] [INFO] Loading io stdlib from cache
console.ts:137 [Extension Host] [INFO] Loading base64 stdlib from cache
console.ts:137 [Extension Host] [INFO] Loading yaml stdlib from cache
console.ts:137 [Extension Host] [INFO] Loading objspace stdlib from cache
console.ts:137 [Extension Host] [INFO] Loading rake stdlib from cache
console.ts:137 [Extension Host] [INFO] Loading open-uri stdlib from cache
console.ts:137 [Extension Host] [INFO] Loading stringio stdlib from cache
console.ts:137 [Extension Host] [INFO] Loading psych stdlib from cache
console.ts:137 [Extension Host] [INFO] Loading racc stdlib from cache
console.ts:137 [Extension Host] [INFO] Loading json stdlib from cache
console.ts:137 [Extension Host] [INFO] Loading rexml stdlib from cache
console.ts:137 [Extension Host] [INFO] Catalog complete (3165 files, 208763 pins)
console.ts:137 [Extension Host] [INFO] Sending response to textDocument/documentSymbol
console.ts:137 [Extension Host] [INFO] Diagnosing file:///Users/sam/projects/fresho/projects/production-apps/fresho-app/app/models/application_record.rb
console.ts:137 [Extension Host] [INFO] Server sent textDocument/publishDiagnostics
console.ts:137 [Extension Host] [INFO] Diagnosing file:///Users/sam/projects/fresho/projects/production-apps/fresho-app/app/models/management/companies/company.rb
console.ts:137 [Extension Host] [INFO] Server sent textDocument/publishDiagnostics
console.ts:137 [Extension Host] [INFO] Diagnosing file:///Users/sam/projects/fresho/projects/production-apps/fresho-app/app/models/system/company.rb
console.ts:137 [Extension Host] [INFO] Server sent textDocument/publishDiagnostics
```

**Comment by castwide** [comment]
Many thanks for the detailed message, and apologies for the late reply.

Does this problem still occur with gem version 0.43.1? My first guess is that the server locked up trying to deliver information about a mapped file based on an incomplete mapping, but some recent optimizations might have fixed that issue.

If the problem persists, please let me know, and another log would definitely be helpful.

**Comment by castwide** [comment]
Gem version 0.43.2 addresses this issue. Server requests should be synchronized to ensure that the request ID gets incremented properly.

**Comment by timfjord** [comment]
Just tested, works like a charm, thanks @castwide

**Comment by samk1** [comment]
Hey! Thanks for getting back, and I really appreciate all the effort that's gone into solargraph so far. Both me and my teammates use solargraph quite heavily and it's a really useful tool.

I had a test on solargraph 0.43.2 and I can't seem to reproduce the issue anymore. I think it's fixed now. Thanks again!

Also, let me know if there's anyway I can contribute to solargraph - I'd like to return the favour for all the help it's been in my workflow.
