### ISSUE TITLE
[RuntimeError] conflicting chdir during another chdir block

### ISSUE THREAD

**Issue by baelter** [castwide/solargraph#481]
In a multi folder workspace I sometimes get:

```
[WARN] /home/anders/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph/documentor.rb:62:in `chdir'/home/anders/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph/documentor.rb:62:in `block in specs_from_bundle'/home/anders/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler.rb:397:in `block in with_unbundled_env'/home/anders/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler.rb:697:in `with_env'/home/anders/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.26/lib/bundler.rb:397:in `with_unbundled_env'/home/anders/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph.rb:66:in `with_clean_env'/home/anders/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph/documentor.rb:61:in `specs_from_bundle'/home/anders/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph/api_map/bundler_methods.rb:14:in `require_from_bundle'/home/anders/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph/yard_map.rb:256:in `process_gemsets'/home/anders/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph/yard_map.rb:193:in `process_requires'/home/anders/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph/yard_map.rb:77:in `change'/home/anders/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph/api_map.rb:68:in `catalog'/home/anders/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph/library.rb:378:in `catalog_inlock'/home/anders/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph/library.rb:59:in `block in attach'/home/anders/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph/library.rb:50:in `synchronize'/home/anders/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph/library.rb:50:in `attach'/home/anders/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph/language_server/host/dispatch.rb:63:in `block in explicit_library_for'/home/anders/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph/language_server/host/dispatch.rb:61:in `each'/home/anders/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph/language_server/host/dispatch.rb:61:in `explicit_library_for'/home/anders/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph/language_server/host/dispatch.rb:41:in `library_for'/home/anders/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph/language_server/host.rb:503:in `formatter_config'/home/anders/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph/language_server/message/text_document/formatting.rb:48:in `config_for'/home/anders/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph/language_server/message/text_document/formatting.rb:15:in `process'/home/anders/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph/language_server/host.rb:103:in `receive'/home/anders/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph/language_server/transport/adapter.rb:44:in `process'/home/anders/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph/language_server/transport/adapter.rb:17:in `block in opening'/home/anders/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph/language_server/transport/data_reader.rb:59:in `parse_message_from_buffer'/home/anders/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph/language_server/transport/data_reader.rb:35:in `block in receive'/home/anders/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph/language_server/transport/data_reader.rb:30:in `each_char'/home/anders/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph/language_server/transport/data_reader.rb:30:in `receive'/home/anders/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/solargraph-0.43.0/lib/solargraph/language_server/transport/adapter.rb:27:in `receiving'/home/anders/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/backport-1.2.0/lib/backport/client.rb:66:in `tick'/home/anders/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/backport-1.2.0/lib/backport/server/tcpip.rb:82:in `update'/home/anders/.rbenv/versions/3.0.2/lib/ruby/3.0.0/observer.rb:222:in `block in notify_observers'/home/anders/.rbenv/versions/3.0.2/lib/ruby/3.0.0/observer.rb:221:in `each'/home/anders/.rbenv/versions/3.0.2/lib/ruby/3.0.0/observer.rb:221:in `notify_observers'/home/anders/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/backport-1.2.0/lib/backport/client.rb:124:in `read_input'/home/anders/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/backport-1.2.0/lib/backport/client.rb:105:in `block in run_input_thread'[INFO] Sending response to textDocument/formatting

[Extension Host] [DEBUG] Content-Length: 123
{"jsonrpc":"2.0","id":1193,"error":{"code":-32603,"message":"[RuntimeError] conflicting chdir during another chdir block"}}
log.ts:295  

WARN Error: [RuntimeError] conflicting chdir during another chdir block
	at handleResponse (vscode-file://vscode-app/home/anders/.vscode/extensions/castwide.solargraph-0.23.0/node_modules/vscode-jsonrpc/lib/common/connection.js:477)
	at processMessageQueue (vscode-file://vscode-app/home/anders/.vscode/extensions/castwide.solargraph-0.23.0/node_modules/vscode-jsonrpc/lib/common/connection.js:292)
	at Immediate.<anonymous> (vscode-file://vscode-app/home/anders/.vscode/extensions/castwide.solargraph-0.23.0/node_modules/vscode-jsonrpc/lib/common/connection.js:276)
	at processImmediate (internal/timers.js:461)
```

**Comment by baelter** [comment]
Related issue: https://bugs.ruby-lang.org/issues/15661

**Comment by castwide** [comment]
My first guess is that your workspaces have dependencies that conflict too much to work in a single Ruby runtime. Solargraph will try to separate dependencies between workspaces, but they all get mapped in the same runtime process, so clashes are definitely possible.

Nonetheless, there might be some other solution to that 'conflicting chdir' error, so I'll look further into it.

**Comment by castwide** [comment]
Does this error still persist with gem version 0.43.2? I haven't been able to reproduce it. A change to server request synchronization may have fixed it, but there's another avenue I can pursue if it's still happening.

**Comment by castwide** [comment]
Quick update: I finally managed to reproduce the error. The other avenue I mentioned looks like the way to go. I'll publish a fix in a patch release.

**Comment by castwide** [comment]
Gem v0.43.3 addresses the conflicting chdir issue.
