### ISSUE TITLE
Solargraph fails to load gems

### ISSUE THREAD

**Issue by strayer** [castwide/solargraph#495]
I'm having trouble with solargraph in a rails project I'm working on that I can't share. A while ago I noticed that rubocop diagnostics and formatting stopped working and I'm unsure why. A lot of things changed in my neovim configuration in the meantime, so I can't say if this was broken by the rails project or my neovim config.

My lsp log shows errors like this:

`[WARN] Failed to load gems from bundle at /Users/strayer/project_path`

```
[INFO] Diagnosing file:///Users/strayer/project_path/lib/utilities/rswag/schema.rb
<Thread:0x00007fbe5f0a56e8 /Users/strayer/.local/share/nvim/lsp_servers/solargraph/gems/solargraph-0.44.0/lib/solargraph/language_server/host/diagnoser.rb:45 run> terminated with exception (report_on_exception is true):
<internal:/Users/strayer/.asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- rubocop-rails (LoadError)
	from <internal:/Users/strayer/.asdf/installs/ruby/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/strayer/.local/share/nvim/lsp_servers/solargraph/gems/rubocop-1.22.1/lib/rubocop/config_loader_resolver.rb:17:in `block (2 levels) in resolve_requires'
	from /Users/strayer/.local/share/nvim/lsp_servers/solargraph/gems/rubocop-1.22.1/lib/rubocop/config_loader_resolver.rb:13:in `each'
	from /Users/strayer/.local/share/nvim/lsp_servers/solargraph/gems/rubocop-1.22.1/lib/rubocop/config_loader_resolver.rb:13:in `block in resolve_requires'
	from <internal:kernel>:90:in `tap'
	from /Users/strayer/.local/share/nvim/lsp_servers/solargraph/gems/rubocop-1.22.1/lib/rubocop/config_loader_resolver.rb:12:in `resolve_requires'
	from /Users/strayer/.local/share/nvim/lsp_servers/solargraph/gems/rubocop-1.22.1/lib/rubocop/config_loader.rb:44:in `load_file'
	from /Users/strayer/.local/share/nvim/lsp_servers/solargraph/gems/rubocop-1.22.1/lib/rubocop/config_loader.rb:103:in `configuration_from_file'
	from /Users/strayer/.local/share/nvim/lsp_servers/solargraph/gems/rubocop-1.22.1/lib/rubocop/config_store.rb:68:in `for_dir'
	from /Users/strayer/.local/share/nvim/lsp_servers/solargraph/gems/rubocop-1.22.1/lib/rubocop/config_store.rb:43:in `for_file'
	from /Users/strayer/.local/share/nvim/lsp_servers/solargraph/gems/rubocop-1.22.1/lib/rubocop/runner.rb:141:in `file_offense_cache'
	from /Users/strayer/.local/share/nvim/lsp_servers/solargraph/gems/rubocop-1.22.1/lib/rubocop/runner.rb:129:in `file_offenses'
	from /Users/strayer/.local/share/nvim/lsp_servers/solargraph/gems/rubocop-1.22.1/lib/rubocop/runner.rb:120:in `process_file'
	from /Users/strayer/.local/share/nvim/lsp_servers/solargraph/gems/rubocop-1.22.1/lib/rubocop/runner.rb:101:in `block in each_inspected_file'
	from /Users/strayer/.local/share/nvim/lsp_servers/solargraph/gems/rubocop-1.22.1/lib/rubocop/runner.rb:100:in `each'
	from /Users/strayer/.local/share/nvim/lsp_servers/solargraph/gems/rubocop-1.22.1/lib/rubocop/runner.rb:100:in `reduce'
	from /Users/strayer/.local/share/nvim/lsp_servers/solargraph/gems/rubocop-1.22.1/lib/rubocop/runner.rb:100:in `each_inspected_file'
	from /Users/strayer/.local/share/nvim/lsp_servers/solargraph/gems/rubocop-1.22.1/lib/rubocop/runner.rb:86:in `inspect_files'
	from /Users/strayer/.local/share/nvim/lsp_servers/solargraph/gems/rubocop-1.22.1/lib/rubocop/runner.rb:47:in `run'
	from /Users/strayer/.local/share/nvim/lsp_servers/solargraph/gems/solargraph-0.44.0/lib/solargraph/diagnostics/rubocop.rb:29:in `block in diagnose'
	from /Users/strayer/.local/share/nvim/lsp_servers/solargraph/gems/solargraph-0.44.0/lib/solargraph/diagnostics/rubocop_helpers.rb:57:in `redirect_stdout'
	from /Users/strayer/.local/share/nvim/lsp_servers/solargraph/gems/solargraph-0.44.0/lib/solargraph/diagnostics/rubocop.rb:29:in `diagnose'
	from /Users/strayer/.local/share/nvim/lsp_servers/solargraph/gems/solargraph-0.44.0/lib/solargraph/library.rb:363:in `block in diagnose'
	from /Users/strayer/.local/share/nvim/lsp_servers/solargraph/gems/solargraph-0.44.0/lib/solargraph/library.rb:362:in `each_pair'
	from /Users/strayer/.local/share/nvim/lsp_servers/solargraph/gems/solargraph-0.44.0/lib/solargraph/library.rb:362:in `diagnose'
	from /Users/strayer/.local/share/nvim/lsp_servers/solargraph/gems/solargraph-0.44.0/lib/solargraph/language_server/host.rb:211:in `diagnose'
	from /Users/strayer/.local/share/nvim/lsp_servers/solargraph/gems/solargraph-0.44.0/lib/solargraph/language_server/host/diagnoser.rb:66:in `tick'
	from /Users/strayer/.local/share/nvim/lsp_servers/solargraph/gems/solargraph-0.44.0/lib/solargraph/language_server/host/diagnoser.rb:47:in `block in start'
```

I tried adding solargraph to the bundler Gemfile (which I can't do permanently since I'm not in control of the project and would like to keep solargraph "external"), but I can't get solargraph to pick up the `useBundler` setting. I can set the logLevel, so nvim-lspconfig does seem to pass the settings to solargraph.

My intention is to install solargraph and solargraph-rails outside of the project with `gem install` and use rubocop and its plugins managed by bundler in the project. I'm unsure if this is even supported, since I noticed solargraph seems to use the included rubocop.

I'm using https://github.com/williamboman/nvim-lsp-installer/ to install solargraph, although I did manage it myself before with the default lspconfig mentioned [here](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#solargraph), same issue then. I can easily stop using nvim-lsp-installer for solargraph and manage solargraph myself again, but I still won't be able to add it to the project with bundler.

**Comment by tomekn** [comment]
+1 to this one, getting the same behaviour on my end. Looking for a workaround, will report back if i manage to find something. Worth noting that this only started happening today for me so it must be some env quirk.

**Comment by jakegerard18** [comment]
Also having this issue. Any updates?

**Comment by jakegerard18** [comment]
Update: Even though I have rubocop installed in my project repo, I installed it in the outer directory I installed solargraph in (i.e. my global gem directory outside of my project repo) and this fixed the issue. I now have linting messages displaying in my project repo code.

**Comment by castwide** [comment]
Closing as resolved. If anyone still has problems with their RuboCop setup, please feel free to open a discussion or a new issue.
