### ISSUE TITLE
How does solargraph determine the methods of an object

### ISSUE THREAD

**Issue by eregon** [castwide/solargraph#501]
Hello,
I've been trying Solargraph on TruffleRuby, and completion works for regular Ruby methods.

However, when trying to complete methods of a "foreign object" (e.g., a Java or JavaScript or Python object), Solargraph fails like this using VSCode (and no completion at all is then provided by Solargraph):
```
[2021-11-15 15:43:35.205] [exthost] [error] [castwide.solargraph] provider FAILED
[2021-11-15 15:43:35.211] [exthost] [error] Canceled: Canceled
	at LanguageClient.makeCancelError (/home/eregon/.vscode/extensions/castwide.solargraph-0.23.0/node_modules/vscode-languageclient/lib/common/client.js:2666:24)
	at LanguageClient.handleFailedRequest (/home/eregon/.vscode/extensions/castwide.solargraph-0.23.0/node_modules/vscode-languageclient/lib/common/client.js:2656:28)
	at /home/eregon/.vscode/extensions/castwide.solargraph-0.23.0/node_modules/vscode-languageclient/lib/common/client.js:858:39
	at async U.provideCompletionItems (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:167606)
```
BTW, is there a way to find out what was the Ruby-level exception that caused this?

Such foreign objects do report foreign methods on TruffleRuby, by defining the `methods` method, for instance:

$ ruby -e 'p Java.type("javax.swing.JFrame").methods'
[:yield_self, :instance_variable_set, :class, :untrust, :==, :send, :respond_to?, :untrusted?, :=~, :instance_exec, :!~, :singleton_methods, :object_id, :equal?, :define_singleton_method, :===, :kind_of?, :trust, :!=, :<=>, :display, :[]=, :instance_variable_defined?, :then, :is_a?, :remove_instance_variable, :public_method, :__id__, :delete, :protected_methods, :tainted?, :freeze, :inspect, :method, :__send__, :untaint, :tap, :nil?, :to_enum, :public_send, :private_methods, :eql?, :singleton_class, :taint, :dup, :instance_eval, :instance_of?, :[], :public_methods, :instance_variable_get, :itself, :frozen?, :instance_variables, :to_s, :singleton_method, :extend, :!, :hash, :new, :enum_for, :methods, :clone, :setDefaultLookAndFeelDecorated, :isDefaultLookAndFeelDecorated, :getFrames, :getWindows, :getOwnerlessWindows]

I looked at https://github.com/castwide/solargraph/blob/master/lib/solargraph/api_map.rb but could not find how solargraph finds out which methods an object has.
Maybe it's done via `ancestors` and `instance_methods/instance_method`?

`instance_methods` seems difficult to support for foreign objects, because we give them the same foreign class, and so that foreign class cannot know which methods the foreign object has, the only way to know is to ask the foreign object.

From https://github.com/oracle/truffleruby/issues/2527

**Comment by castwide** [comment]
This isn't currently possible with Solargraph. It uses static analysis to find methods, so methods defined at runtime aren't visible. There are ways to document dynamic methods with YARD (e.g., the `@!method` directive), but there would still need to be a mechanism for Solargraph to infer the correct class from a `Java.type` call.

**Comment by YU5Z8X2CvH1fv4ep** [comment]
The methods and internal functions of the java object support static analysis. Can you read the type from ruby ​​and then request the API of the java language server to obtain the code completion of the ruby ​​(from java) object? The premise is that the ruby ​​language server can Know that an object comes from java. This is an idea

**Comment by YU5Z8X2CvH1fv4ep** [comment]
Theoretically achievable

**Comment by castwide** [comment]
It's definitely theoretically achievable, but it's beyond the scope of Solargraph itself. TruffleRuby support would have to be accomplished in a plugin. I would rather not try to support Java integration as a first-class feature. I can try to provide help developing a plugin, but I don't want responsibility for its maintenance.

**Comment by YU5Z8X2CvH1fv4ep** [comment]
> It's definitely theoretically achievable, but it's beyond the scope of Solargraph itself. TruffleRuby support would have to be accomplished in a plugin. I would rather not try to support Java integration as a first-class feature. I can try to provide help developing a plugin, but I don't want responsibility for its maintenance.

Is there any relevant documentation written by the Solargraph plugin?

**Comment by YU5Z8X2CvH1fv4ep** [comment]
i find some docment in https://solargraph.org/guides/plugins. but i dont know how can i get a type of ruby variable  . if i can get ruby object type , work will be simple .

**Comment by castwide** [comment]
You probably want your plugin to modify the ApiMap with a Convention. You can see existing implementations in `lib/solargraph/convention` and the [solargraph-rails](https://github.com/iftheshoefritz/solargraph-rails) plugin.

**Comment by YU5Z8X2CvH1fv4ep** [comment]
> You probably want your plugin to modify the ApiMap with a Convention. You can see existing implementations in `lib/solargraph/convention` and the [solargraph-rails](https://github.com/iftheshoefritz/solargraph-rails) plugin.

thank?i try it on free time
