### ISSUE TITLE
New release 0.44.1 has introduced an UnhandledRejection error

### ISSUE THREAD

**Issue by albertoleal** [castwide/solargraph#505]
After upgrading to the latest version, whenever I open a ruby file on nvim I receive the following error:

```
[coc.nvim]: UnhandledRejection: Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:399:19)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at /Users/aleal/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:35:3107
    at new Promise (<anonymous>)
    at DF.write (/Users/aleal/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:35:3028)
    at QS.doWrite (/Users/aleal/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:36:1698)
    at /Users/aleal/.local/share/nvim/site/pack/packer/start/coc.nvim/build/index.js:36:1597
```

I downgraded to the previous version, v0.44.0, and the error disappeared.

**Comment by castwide** [comment]
Does the error still happen with v0.44.2? If so, is there any way you can get a log from the Solargraph server process?

**Comment by albertoleal** [comment]
@castwide It works great on v0.44.2! Thanks for that :)
