### ISSUE TITLE
Setup/configs - couldn't get solargraph working

### ISSUE THREAD

**Issue by scorpion35** [castwide/solargraph#526]
Hello! I am on a mac and couldn't get Solargraph to work. Here's what I have -

<details>
<summary>`~/.zshrc` config</summary>

```zsh
<... other settings>
# export RBENV_DEBUG=false
export RBENV_SHELL="zsh"
export RBENV_VERSION="3.0.3"
export RBENV_ROOT="$HOME/Documents/.rbenv_$RBENV_VERSION"
export GEM_HOME="$RBENV_ROOT/local-gems"
export GEM_PATH="$GEM_HOME/bin"
export GEM_SPEC_CACHE="$GEM_HOME/specifications"
export GEM_BIN_DIR="$GEM_PATH"
# export PATH="$GEM_HOME:$PATH"
export BUNDLE_PATH="$RBENV_ROOT"
export BUNDLER_VERSION='2.3.3'

eval "$(rbenv init - zsh)"
eval "$(rbenv global $RBENV_VERSION)"
```

</details>

<br>

### System wide setup

- Installed Ruby - `rbenv install 3.0.3`
- Updated system gems - `gem update --system` # 3.3.3
- Installed Bundler - `gem install bundler:2.3.3`
- Installed Rubocop - `gem install rubocop`
- Installed Solargraph - `gem install solargraph` # installed 0.44.2

<br>

### Project setup

<details>
<summary>`<project path>/Gemfile`</summary>

```ruby
# frozen_string_literal: true
source "https://rubygems.org"
gem "rake", "~> 13.0", require: true
gem "rspec", "~> 3.0", require: true

group :development do
gem "rubocop", "~> 1.23.0"
gem "rubocop-rake", "~> 0.6.0"
gem "rubocop-rspec", "~> 2.6.0"

gem "solargraph", "~> 0.44.2"

gem "byebug", "~> 11.1", require: true
end
```

</details>

<details>
<summary>`<project path>/.bundle/config`</summary>
```bash
---
BUNDLE_BIN: "bin"
BUNDLE_WITH: "development"
```
</details>

<details>
<summary>`gem env`</summary>

RubyGems Environment:

- RUBYGEMS VERSION: 3.3.3
- RUBY VERSION: 3.0.3 (2021-11-24 patchlevel 157) [arm64-darwin21]
- INSTALLATION DIRECTORY: /Users/panne/Documents/.rbenv_3.0.3/local-gems
- USER INSTALLATION DIRECTORY: /Users/panne/.gem/ruby/3.0.0
- RUBY EXECUTABLE: /Users/panne/Documents/.rbenv_3.0.3/versions/3.0.3/bin/ruby
- GIT EXECUTABLE: /opt/homebrew/bin/git
- EXECUTABLE DIRECTORY: /Users/panne/Documents/.rbenv_3.0.3/local-gems/bin
- SPEC CACHE DIRECTORY: /Users/panne/Documents/.rbenv_3.0.3/local-gems/specifications
- SYSTEM CONFIGURATION DIRECTORY: /Users/panne/Documents/.rbenv_3.0.3/versions/3.0.3/etc
- RUBYGEMS PLATFORMS:
  - ruby
  - arm64-darwin-21
- GEM PATHS:
  - /Users/panne/Documents/.rbenv_3.0.3/local-gems
  - /Users/panne/Documents/.rbenv_3.0.3/local-gems/bin
- GEM CONFIGURATION:
  - :update_sources => true
  - :verbose => true
  - :backtrace => false
  - :bulk_threshold => 1000
- REMOTE SOURCES:
  - https://rubygems.org/
- SHELL PATH:
  - /Users/panne/Documents/.rbenv_3.0.3/versions/3.0.3/bin
  - /opt/homebrew/Cellar/rbenv/1.2.0/libexec
  - /Users/panne/Documents/.rbenv_3.0.3/shims
  - /Users/panne/.nvm/versions/node/v16.13.1/bin
  - /opt/homebrew/bin
  - /opt/homebrew/sbin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /usr/local/share/dotnet
  - ~/.dotnet/tools
  - /Library/Apple/usr/bin
  - /Library/Frameworks/Mono.framework/Versions/Current/Commands
  - /Users/panne/Documents/Personal/algos/bin

</details>

<details>
<summary>`<project path>/.vscode/settings.json`</summary>
```json
    ```{
    // Formatters
    "editor.formatOnSave": true,

    "[json]": {
        "editor.quickSuggestions": {
        "strings": true
        },
        "editor.suggest.insertMode": "replace",
        "gitlens.codeLens.scopes": ["document"],
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },

    "[ruby]": {
        "editor.defaultFormatter": "misogi.ruby-rubocop"
    },

    // Rubocop
    "ruby.format": "rubocop",
    "ruby.useBundler": true,
    "ruby.pathToBundler": "bundle",
    "ruby.useLanguageServer": true,
    "ruby.languageServer": {
        "logLevel": "warn"
    },
    "ruby.rubocop.useBundler": true,
    "ruby.rubocop.onSave": true,
    // "ruby.rubocop.configFilePath": "./.rubocop.yml",
    "ruby.rubocop.executePath": "bin/",

    // Solargraph
    "solargraph.useBundler": false,
    "solargraph.completion": true,
    "solargraph.formatting": true,
    "solargraph.logLevel": "debug",
    "solargraph.checkGemVersion": true,
    "solargraph.autoformat": true,
    // "solargraph.bundlerPath": "bin/",
    "solargraph.commandPath": "bin/solargraph",
    "solargraph.hover": true,
    "solargraph.rename": true,

    // Terminal settings
    "terminal.integrated.defaultProfile.osx": "zsh",
    "terminal.integrated.automationProfile.osx": {
        "path": "/bin/zsh",
        "icon": "beaker"
    },
    "terminal.integrated.env.osx": {
        "PATH": "${workspaceFolder}/bin:${env:PATH}"
    }
    }
    ```

</details>

<br>

Installed vscode extensions as well - `rubocop`, `solargraph`, `ruby`, and some other extensions ...

And finally, I opened a new terminal in `vscode` and ran `bundle install`

<details>
<summary>`bundle info bundler`</summary>
```bash
  * bundler (2.3.3)
        Summary: The best way to manage your application's dependencies
        Homepage: https://bundler.io
        Source Code: https://github.com/rubygems/rubygems/
        Changelog: https://github.com/rubygems/rubygems/blob/master/bundler/CHANGELOG.md
        Bug Tracker: https://github.com/rubygems/rubygems/issues?q=is%3Aopen+is%3Aissue+label%3ABundler
        Path: /Users/panne/Documents/.rbenv_3.0.3/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.3.3
        Default Gem: yes
```
</details>

<details>
<summary>`bundle info solargraph`</summary>
```bash
  * solargraph (0.44.2)
        Summary: A Ruby language server
        Homepage: http://solargraph.org
        Path: /Users/panne/Documents/.rbenv_3.0.3/ruby/3.0.0/gems/solargraph-0.44.2
```
</details>

Solargraph would never start for me, and I get the following message when I try to run `solargraph bundle`

```ruby
/Users/panne/Documents/.rbenv_3.0.3/local-gems/gems/bundler-2.3.3/lib/bundler/definition.rb:487:in `block in materialize': uninitialized constant Bundler::Definition::Bundle (NameError)
        from /Users/panne/Documents/.rbenv_3.0.3/local-gems/gems/bundler-2.3.3/lib/bundler/definition.rb:485:in `each'
        from /Users/panne/Documents/.rbenv_3.0.3/local-gems/gems/bundler-2.3.3/lib/bundler/definition.rb:485:in `materialize'
        from /Users/panne/Documents/.rbenv_3.0.3/local-gems/gems/bundler-2.3.3/lib/bundler/definition.rb:243:in `specs_for'
        from -e:1:in `block in <main>'
        from -e:1:in `chdir'
        from -e:1:in `<main>'

[Solargraph::BundleNotFoundError] Failed to load gems from bundle at .
No bundled gems are available in .
```

Solargraph's vscode extension also fails with several errors
![image](https://user-images.githubusercontent.com/18679225/147476470-4631aaa3-49ed-4ed0-b166-233244f84d16.png)

**Comment by castwide** [comment]
The problem might be related to the `solargraph.comandPath` setting. It looks like you're running a customized binary that VS Code finds at `~/Documents/Personal/algos/bin/solargraph`, which starts with Ruby 2.6 (most likely a system installation of Ruby instead of an rbenv version), and switches to the rbenv installation of Ruby 3.0.3 at some point. I'm not sure what needs to be done, but that's where I'd start looking for the root cause of the problem.

**Comment by scorpion35** [comment]
> The problem might be related to the `solargraph.comandPath` setting. It looks like you're running a customized binary that VS Code finds at `~/Documents/Personal/algos/bin/solargraph`, which starts with Ruby 2.6 (most likely a system installation of Ruby instead of an rbenv version), and switches to the rbenv installation of Ruby 3.0.3 at some point. I'm not sure what needs to be done, but that's where I'd start looking for the root cause of the problem.

I launched a new terminal with proper `env` setup, and can confirm the terminal is using correct ruby version
![image](https://user-images.githubusercontent.com/18679225/147826042-28e184f6-f75a-42a0-ad43-539de6e3f89c.png)


Do you think it could be a rbenv or bundler's issue?

**Comment by castwide** [comment]
> I launched a new terminal with proper `env` setup, and can confirm the terminal is using correct ruby version ![image](https://user-images.githubusercontent.com/18679225/147826042-28e184f6-f75a-42a0-ad43-539de6e3f89c.png)

You might need to run `bundle install` again. Since Solargraph is in your Gemfile, you could also try setting `solargraph.useBundler` to `true` in `.vscode/settings.json`.

> I also tried to debug the [vscode-solargraph](https://github.com/castwide/vscode-solargraph) vscode extension, but couldn't get breakpoints to work when I launch a debug vscode. Looks like `.vscode/tasks.json` is missing? Could you add the file with the task configured when you get a min please?

No problem. I updated the vscode-solargraph repo to include the entire .vscode directory.

> Happy new year Fred! 🎉 Thank you very much for your awesome work :)

**Comment by Eusebius1920** [comment]
I am seeing the same error but with a different setup.

Solargraph runs in a docker-container (where only one ruby is globally installed - no rvm or rbenv).

`ruby --version` show correct ruby version (3.0.2)

But
`bundle exec solargraph scan` gives:

```
user@cdfc3cdd716f:/app$ bundle exec solargraph scan
[WARN] /usr/local/bundle/gems/bundler-2.2.33/lib/bundler/definition.rb:480:in `materialize': Could not find rails-7.0.2.2, puma-5.6.2, jbuilder-2.11.5, bootsnap-1.9.4, jwt-2.3.0, shakapacker-6.1.1, faraday-1.9.3, actioncable-7.0.2.2, actionmailbox-7.0.2.2, actionmailer-7.0.2.2, actionpack-7.0.2.2, actiontext-7.0.2.2, actionview-7.0.2.2, activejob-7.0.2.2, activemodel-7.0.2.2, activerecord-7.0.2.2, activestorage-7.0.2.2, activesupport-7.0.2.2, railties-7.0.2.2, hashie-5.0.0, i18n-1.10.0, faraday-multipart-1.0.3, faraday-retry-1.0.3, nokogiri-1.13.3, zeitwerk-2.5.4, loofah-2.14.0, mini_portile2-2.8.0 in any of the sources (Bundler::GemNotFound)
	from /usr/local/bundle/gems/bundler-2.2.33/lib/bundler/definition.rb:235:in `specs_for'
	from -e:1:in `block in <main>'
	from -e:1:in `chdir'
	from -e:1:in `<main>'

[WARN] Failed to load gems from bundle at /app
Scanned /app (36298 pins) in 17.937281454000185 seconds.
```

Newest solargraph is bundled via Gemfile (development-group), bundle install was run and running it again wont help. Rails itself runs fine with the bundle, `bundle exec gem list` lists the "missing" gems above in the correct version.

**Comment by Eusebius1920** [comment]
**Addendum:** This exact setup was working before with solargraph 0.43.0, but downgrading solargraph does not solve the issue. Maybe it is due to a ruby or bundler version.
