### ISSUE TITLE
Intermittent errors with deoplete/neovim/deoplete-solargraph

### ISSUE THREAD

**Issue by bowmanmike** [castwide/solargraph#53]
I've been using solargraph with the deoplete source for neovim for a few weeks with no problems. Last week I started seeing errors occasionally when I'm editing a Ruby file. It seems to be related to the solargraph server itself.

```
[deoplete] NoneType: None
{'status': 'err', 'message': "undefined method `docstring' for #<Solargraph::Pin::Symbol:0x007ff33a810710>\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/solargraph-0.20.0/lib/solargraph/suggestion.rb:175:in `pull'\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/solargraph-0.20.0/lib/so
largraph/server.rb:104:in `block (2 levels) in <class:Server>'\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/solargraph-0.20.0/lib/solargraph/server.rb:104:in `map'\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/solargraph-0.20.0/lib/solargraph/server.rb:104:in `block in <class:Server
>'\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1634:in `call'\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1634:in `block in compile!'\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sinatra-2.0.1/l
ib/sinatra/base.rb:992:in `block (3 levels) in route!'\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1011:in `route_eval'\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:992:in `block (2 levels) in route!'\n/Users/mbow
man/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1039:in `block in process_route'\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1037:in `catch'\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatr
a/base.rb:1037:in `process_route'\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:990:in `block in route!'\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:989:in `each'\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/gems
/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:989:in `route!'\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1096:in `block in dispatch!'\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `block in invoke'\n/Users
/mbowman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `catch'\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `invoke'\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1
093:in `dispatch!'\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `block in call!'\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `block in invoke'\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3
.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `catch'\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1075:in `invoke'\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:924:in `call!'\n/Users/mbowman/.rbenv/versions/2.
3.1/lib/ruby/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:913:in `call'\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.1/lib/rack/protection/xss_header.rb:18:in `call'\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.1/lib/rack/protection/path
_traversal.rb:16:in `call'\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.1/lib/rack/protection/json_csrf.rb:26:in `call'\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.1/lib/rack/protection/base.rb:50:in `call'\n/Users/mbowman/.rbenv/versions/2.
3.1/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.1/lib/rack/protection/base.rb:50:in `call'\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-protection-2.0.1/lib/rack/protection/frame_options.rb:31:in `call'\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/gems/
.3.0/gems/rack-2.0.4/lib/rack/null_logger.rb:9:in `call'\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.4/lib/rack/head.rb:12:in `call'\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/show_exceptions.rb:22:in `call'\n/Users/mbowman/.rbenv/versions/2.3.
1/lib/ruby/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:194:in `call'\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1957:in `call'\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1501:in `block in call'\n/Users/mb
owman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1728:in `synchronize'\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/sinatra-2.0.1/lib/sinatra/base.rb:1501:in `call'\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.4/lib/rack/handler/webric
k.rb:86:in `service'\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'\n/Users/mbowman/.rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'"}.
```

**Comment by castwide** [comment]
Related issue: https://github.com/uplus/deoplete-solargraph/issues/5

I'm going to close this one for now, as it's an integration issue instead of a bug in Solargraph itself. I'm happy to help with updating clients to use LSP, but that can be handled in other, more specific issues.
