### ISSUE TITLE
Solargraph fails to start in project with old bundler version

### ISSUE THREAD

**Issue by whollingsworth** [castwide/solargraph#530]
I'm hoping to use Solargraph for some Rails projects at work.  I'm using Neovim and a plugin to install language servers, so I'm not 100% certain where the issue lies, but solargraph is failing to start.

```
[ERROR][2022-01-04 14:23:50] .../vim/lsp/rpc.lua:420	"rpc"	"solargraph"	"stderr"	"/Users/whollingsworth/.rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb:1406:in `rescue in block in activate_dependencies': Could not find 'bundler' (>= 1.17.2) among 74 total gem(s) (Gem::MissingSpecError)\nChecked in 'GEM_PATH=/Users/whollingsworth/.local/share/nvim/lsp_servers/solargraph' at: /Users/whollingsworth/.local/share/nvim/lsp_servers/solargraph/specifications/solargraph-0.44.2.gemspec, execute `gem env` for more information\n\tfrom /Users/whollingsworth/.rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb:1403:in `block in activate_dependencies'\n\tfrom /Users/whollingsworth/.rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb:1392:in `each'\n\tfrom /Users/whollingsworth/.rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb:1392:in `activate_dependencies'\n\tfrom /Users/whollingsworth/.rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb:1374:in `activate'\n\tfrom /Users/whollingsworth/.rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems.rb:299:in `block in activate_bin_path'\n\tfrom /Users/whollingsworth/.rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems.rb:298:in `synchronize'\n\tfrom /Users/whollingsworth/.rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems.rb:298:in `activate_bin_path'\n\tfrom /Users/whollingsworth/.local/share/nvim/lsp_servers/solargraph/bin/solargraph:25:in `<main>'\n"
[ERROR][2022-01-04 14:23:50] .../vim/lsp/rpc.lua:420	"rpc"	"solargraph"	"stderr"	"/Users/whollingsworth/.rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'bundler' (1.17.3) required by your /Users/whollingsworth/…/Gemfile.lock. (Gem::MissingSpecVersionError)\nTo update to the latest version installed on your system, run `bundle update --bundler`.\nTo install the missing version, run `gem install bundler:1.17.3`\nChecked in 'GEM_PATH=/Users/whollingsworth/.local/share/nvim/lsp_servers/solargraph' , execute `gem env` for more information\n\tfrom /Users/whollingsworth/.rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb:1404:in `block in activate_dependencies'\n\tfrom /Users/whollingsworth/.rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb:1392:in `each'\n\tfrom /Users/whollingsworth/.rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb:1392:in `activate_dependencies'\n\tfrom /Users/whollingsworth/.rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb:1374:in `activate'\n\tfrom /Users/whollingsworth/.rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems.rb:299:in `block in activate_bin_path'\n\tfrom /Users/whollingsworth/.rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems.rb:298:in `synchronize'\n\tfrom /Users/whollingsworth/.rubies/ruby-2.7.2/lib/ruby/site_ruby/2.7.0/rubygems.rb:298:in `activate_bin_path'\n\tfrom /Users/whollingsworth/.local/share/nvim/lsp_servers/solargraph/bin/solargraph:25:in `<main>'\n"
```

The project is using bundler 1.17.3, but the language server installer pulls in bundler 2.3.4 into the installation directory. If I follow the suggestion and update bundler for the project to the latest version, the server is able to launch successfully. However, this isn't a long term solution for me since I'm not able to change the version of bundler we are using.

Wondering if this is the expected behavior, the result of the plugin using a separate `$GEM_PATH`, or something else?

**Comment by alisnic** [comment]
@whollingsworth you can run solargraph without `bundle exec`, and just use whichever bundler you have in the system

**Comment by whollingsworth** [comment]
Thanks for the suggestion!  If I'm understanding what `useBundler` does correctly, I think the plugin I'm using to manage language servers might already be doing this:

```lua
return {properties = {["solargraph.autoformat"] = {default = false,description = "Enable automatic formatting while typing (WARNING: experimental)",enum = { true,
false },type = { "boolean" }},["solargraph.bundlerPath"] = {default = "bundle",description = "Path to the bundle executable, defaults to 'bundle'. Needs to be an abs
olute path for the 'bundle' exec/shim",scope = "resource",type = "string"},["solargraph.checkGemVersion"] = {default = true,description = "Automatically check if a n
ew version of the Solargraph gem is available.",enum = { true, false },type = "boolean"},["solargraph.commandPath"] = {default = "solargraph",description = "Path to
the solargraph command.  Set this to an absolute path to select from multiple installed Ruby versions.",scope = "resource",type = "string"},["solargraph.completion"]
 = {default = true,description = "Enable completion",enum = { true, false },type = { "boolean" }},["solargraph.definitions"] = {default = true,description = "Enable
definitions (go to, etc.)",enum = { true, false },type = { "boolean" }},["solargraph.diagnostics"] = {default = false,description = "Enable diagnostics",enum = { tru
e, false },type = { "boolean" }},["solargraph.externalServer"] = {default = {host = "localhost",port = 7658},description = "The host and port to use for external tra
nsports. (Ignored for stdio and socket transports.)",properties = {host = {default = "localhost",type = "string"},port = {default = 7658,type = "integer"}},type = "o
bject"},["solargraph.folding"] = {default = true,description = "Enable folding ranges",type = "boolean"},["solargraph.formatting"] = {default = false,description = "
Enable document formatting",enum = { true, false },type = { "boolean" }},["solargraph.hover"] = {default = true,description = "Enable hover",enum = { true, false },t
ype = { "boolean" }},["solargraph.logLevel"] = {default = "warn",description = "Level of debug info to log. `warn` is least and `debug` is most.",enum = { "warn", "i
nfo", "debug" },type = "string"},["solargraph.references"] = {default = true,description = "Enable finding references",enum = { true, false },type = { "boolean" }},[
"solargraph.rename"] = {default = true,description = "Enable symbol renaming",enum = { true, false },type = { "boolean" }},["solargraph.symbols"] = {default = true,d
escription = "Enable symbols",enum = { true, false },type = { "boolean" }},["solargraph.transport"] = {default = "socket",description = "The type of transport to use
.",enum = { "socket", "stdio", "external" },type = "string"},["solargraph.useBundler"] = {default = false,description = "Use `bundle exec` to run solargraph. (If thi
s is true, the solargraph.commandPath setting is ignored.)",type = "boolean"}},title = "Solargraph settings for Ruby"}
```

Maybe I ought to look at the rest of these options for clues.

**Comment by whollingsworth** [comment]
I ended up giving up on the installer plugin and decided to just manage the installation and configuration myself.  Everything's good now, so I'm going to close the issue.
