### ISSUE TITLE
SystemStackError "stack level too deep" on large project

### ISSUE THREAD

**Issue by jeraki** [castwide/solargraph#575]
Hello!

I've got a very large Rails project and Solargraph is crashing while mapping the workspace.

I'm using Neovim with [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig), and when I open my project, I get LSP messages that Solargraph is mapping the workspace, but it hangs forever at 70% complete (3684 of 5262 files, which is only a little bit larger than Solargraph's default maximum file limit of 5000). Looking in Neovim's LSP logs, I see this:

```

[ERROR][2022-08-02 14:51:21] .../vim/lsp/rpc.lua:420	"rpc"	"solargraph"	"stderr"	"Solargraph is listening on stdio PID=32512\n"
[ERROR][2022-08-02 14:52:40] .../vim/lsp/rpc.lua:420	"rpc"	"solargraph"	"stderr"	"#<Thread:0x00007ff08eaab2f8@/redacted/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/solargraph-0.45.0/lib/solargraph/language_server/host/message_worker.rb:43 run> terminated with exception (report_on_exception is true):\n"
[ERROR][2022-08-02 14:52:40] .../vim/lsp/rpc.lua:420	"rpc"	"solargraph"	"stderr"	"/redacted/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/solargraph-0.45.0/lib/solargraph/parser/node_processor.rb:37:in `new': stack level too deep (SystemStackError)\n"
[ERROR][2022-08-02 14:52:40] .../vim/lsp/rpc.lua:420	"rpc"	"solargraph"	"stderr"	"\tfrom /redacted/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/solargraph-0.45.0/lib/solargraph/parser/node_processor.rb:37:in `process'\n\tfrom /redacted/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/solargraph-0.45.0/lib/solargraph/parser/node_processor/base.rb:46:in `block in process_children'\n\tfrom /redacted/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/solargraph-0.45.0/lib/solargraph/parser/node_processor/base.rb:44:in `each'\n\tfrom /redacted/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/solargraph-0.45.0/lib/solargraph/parser/node_processor/base.rb:44:in `process_children'\n\tfrom /redacted/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/solargraph-0.45.0/lib/solargraph/parser/node_processor/base.rb:34:in `process'\n\tfrom /redacted/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/solargraph-0.45.0/lib/solargraph/parser/node_processor.rb:38:in `process'\n\tfrom /redacted/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/solargraph-0.45.0/lib/solargraph/parser/node_processor/base.rb:46:in `block in process_children'\n\tfrom /redacted/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/solargraph-0.45.0/lib/solargraph/parser/node_processor/base.rb:44:in `each'\n\t ... 607 levels...\n\tfrom /redacted/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/solargraph-0.45.0/lib/solargraph/language_server/request.rb:16:in `process'\n\tfrom /redacted/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/solargraph-0.45.0/lib/solargraph/language_server/host.rb:121:in `receive'\n\tfrom /redacted/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/solargraph-0.45.0/lib/solargraph/language_server/host/message_worker.rb:53:in `tick'\n\tfrom /redacted/.rbenv/versions/2.6.7/lib/ruby/gems/2.6.0/gems/solargraph-0.45.0/lib/solargraph/language_server/host/message_worker.rb:44:in `block in start'\n"
```
My `.solargraph.yml` file has the following contents:

```yml
---
include:
- "app/**/*.rb"
- "lib/**/*.rb"
require: []
domains: []
reporters:
formatter:
require_paths: []
plugins: []
max_files: 0
```

I'm also disabling both formatting and diagnostics via nvim-lspconfig's configuration, in case that's relevant:

```lua
lspconfig.solargraph.setup({
  init_options = {
    formatting = false,
  },
  settings = {
    solargraph = {
      diagnostics = false,
    },
  },
})
```

Running `time solargraph scan -v` on the project (per the suggestion on https://solargraph.org/guides/scanning-workspaces) does not crash, but takes a very long time (41 minutes) and pegs one of my CPU cores at 100% the whole time. Obviously I can't include the entire output of this command (both due to size and references to proprietary code), but it ends with this:

```
Scanned /path/to/my/project (353281 pins) in 2486.781297000125 seconds.

real	41m28.087s
user	41m13.299s
sys	0m11.013s
```

I've read https://solargraph.org/guides/performance and have already limited the directories of my project that are included in the workspace. I'm not sure the suggestion of multiple workspaces is feasible for me because my project is not separated into logically distinct sub-applications.

Any suggestions on how I can determine if there's something specific to my project's code that's causing Solargraph to blow the stack? Or might my project just be too large for Solargraph and out of scope for how it's intended to work? Thank you for your time and for your work on Solargraph!

**Comment by castwide** [comment]
You might be able to identify which file triggered the error by setting `logLevel` to `debug` in either `init_options` or `settings.solargraph`. It should be the last message like "Mapping path/to/file.rb" before the error.

**Comment by castwide** [comment]
Cool, glad that worked.

Determining a minimal reproduction might be tricky, especially since `solargraph scan` didn't trigger the same error. If you have the patience, you can try running it again and looking for a pin that takes an especially long time to process. Another option is to create a workspace containing nothing but the problematic file and reduce it until you can pinpoint the problematic node. Sorry I don't have a better solution. If emailing the file to me is an option, I might be able to help more.

**Comment by castwide** [comment]
Thanks for finding a reproducible error. The `when` conditions are recursive in the AST, so I probably need to find a more efficient way to handle them in `NodeProcessors`.
