### ISSUE TITLE
Rubocop doesn't work when has require

### ISSUE THREAD

**Issue by otavioschwanck** [castwide/solargraph#609]
Log: 
```
[ERROR][2022-10-20 20:10:02] .../vim/lsp/rpc.lua:733	"rpc"	"solargraph"	"stderr"	"#<Thread:0x00000001309b34b8 /Users/my_user/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/solargraph-0.44.3/lib/solargraph/language_server/host/diagnoser.rb:45 run> terminated with exception (report_on_exception is true):\n/Users/my_user/.rbenv/versions/2.7.3/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- rubocop-project-name (LoadError)\n\tfrom /Users/my_user/.rbenv/versions/2.7.3/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'\n\tfrom /Users/my_user/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.27.0/lib/rubocop/config_loader_resolver.rb:17:in `block (2 levels) in resolve_requires'\n\tfrom /Users/my_user/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.27.0/lib/rubocop/config_loader_resolver.rb:13:in `each'\n\tfrom /Users/my_user/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.27.0/lib/rubocop/config_loader_resolver.rb:13:in `block in resolve_requires'\n\tfrom /Users/my_user/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.27.0/lib/rubocop/config_loader_resolver.rb:12:in `tap'\n\tfrom /Users/my_user/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.27.0/lib/rubocop/config_loader_resolver.rb:12:in `resolve_requires'\n\tfrom /Users/my_user/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.27.0/lib/rubocop/config_loader.rb:44:in `load_file'\n\tfrom /Users/my_user/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.27.0/lib/rubocop/config_loader.rb:103:in `configuration_from_file'\n\tfrom /Users/my_user/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.27.0/lib/rubocop/config_store.rb:68:in `for_dir'\n\tfrom /Users/my_user/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.27.0/lib/rubocop/config_store.rb:58:in `for'\n\tfrom /Users/my_user/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.27.0/lib/rubocop/target_finder.rb:190:in `block in process_explicit_path'\n\tfrom /Users/my_user/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.27.0/lib/rubocop/target_finder.rb:189:in `reject'\n\tfrom /Users/my_user/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.27.0/lib/rubocop/target_finder.rb:189:in `process_explicit_path'\n\tfrom /Users/my_user/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.27.0/lib/rubocop/target_finder.rb:40:in `block in find'\n\tfrom /Users/my_user/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.27.0/lib/rubocop/target_finder.rb:36:in `each'\n\tfrom /Users/my_user/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.27.0/lib/rubocop/target_finder.rb:36:in `find'\n\tfrom /Users/my_user/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.27.0/lib/rubocop/runner.rb:77:in `find_target_files'\n\tfrom /Users/my_user/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rubocop-1.27.0/lib/rubocop/runner.rb:42:in `run'\n\tfrom /Users/my_user/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/solargraph-0.44.3/lib/solargraph/diagnostics/rubocop.rb:29:in `block in diagnose'\n\tfrom /Users/my_user/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/solargraph-0.44.3/lib/solargraph/diagnostics/rubocop_helpers.rb:57:in `redirect_stdout'\n\tfrom /Users/my_user/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/solargraph-0.44.3/lib/solargraph/diagnostics/rubocop.rb:29:in `diagnose'\n\tfrom /Users/my_user/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/solargraph-0.44.3/lib/solargraph/library.rb:363:in `block in diagnose'\n\tfrom /Users/my_user/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/solargraph-0.44.3/lib/solargraph/library.rb:362:in `each_pair'\n\tfrom /Users/my_user/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/solargraph-0.44.3/lib/solargraph/library.rb:362:in `diagnose'\n\tfrom /Users/my_user/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/solargraph-0.44.3/lib/solargraph/language_server/host.rb:211:in `diagnose'\n\tfrom /Users/my_user/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/solargraph-0.44.3/lib/solargraph/language_server/host/diagnoser.rb:66:in `tick'\n\tfrom /Users/my_user/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/solargraph-0.44.3/lib/solargraph/language_server/host/diagnoser.rb:47:in `block in start'\n"```

On rubocop:
```yaml
require:
  - rubocop-gitlab-security
  - rubocop-project_name
  - rubocop-performance
  - rubocop-rails
  ```
  
  im using diagnosticls (https://github.com/iamcco/diagnostic-languageserver) to make rubocop work (and disabled from solargraph).
  
  My diagnosticls config:
  ```
  lspconfig.diagnosticls.setup {
  filetypes = { "ruby" },
  single_file_support = false,
  init_options = {
    linters = {
      rubocop = {
        command = "bundle",
        sourceName = "rubocop",
        debounce = 100,
        args = { "exec",
          "rubocop",
          "--format",
          "json",
          "--force-exclusion",
          "--stdin",
          "%filepath"
        },
        parseJson = {
          errorsRoot = "files[0].offenses",
          line = "location.start_line",
          endLine = "location.last_line",
          column = "location.start_column",
          endColumn = "location.end_column",
          message = "[${cop_name}] ${message}",
          security = "severity"
        },
        securities = {
          fatal = "error",
          error = "error",
          warning = "warning",
          convention = "info",
          refactor = "info",
          info = "info"
        }
      },
      shellcheck = {
        command = "shellcheck",
        debounce = 100,
        args = { "--format=gcc", "-"},
        offsetLine = 0,
        offsetColumn = 0,
        sourceName = "shellcheck",
        formatLines = 1,
        formatPattern = {
          "^[^:]+:(\\d+):(\\d+):\\s+([^:]+):\\s+(.*)$",
          {
            line = 1,
            column = 2,
            message = 4,
            security = 3
          }
        },
        securities = {
          error = "error",
          warning = "warning",
          note = "info"
        }
      },
      languagetool = {
        command = "languagetool",
        debounce = 200,
        args = {"-"},
        offsetLine = 0,
        offsetColumn = 0,
        sourceName = "languagetool",
        formatLines = 2,
        formatPattern = {
          "^\\d+?\\.\\)\\s+Line\\s+(\\d+),\\s+column\\s+(\\d+),\\s+([^\\n]+)\nMessage:\\s+(.*)$",
          {
            line = 1,
            column = 2,
            message = { 4, 3 }
          }
        }
      }
    },
    formatters = {
      dartfmt = {
        command = "dartfmt",
        args = { "--fix" }
      },
      rubocop = {
        command = "bundle",
        args = { "exec",
          "rubocop",
          "-a",
          "%filepath",
          ">",
          "tmp/rubocop"
        }
      }
    },
    filetypes = {
      sh = "shellcheck",
      email = "languagetool",
      ruby = "rubocop"
    },
    formatFiletypes = {
      dart = "dartfmt",
      ruby = "rubocop"
    }
  }
}
```

**Comment by grncdr** [comment]
The error says:

```
 `require': cannot load such file -- rubocop-project-name
 ```
 
 The `requires` list in your Rubocop config has:
 
 ```yaml
   - rubocop-project_name
 ```
 
 (note the difference between the names)
 
 ---
 
 As far as I can tell, neither of these are public gems. Can you share the contents of your `.solargraph.yml` ?

**Comment by otavioschwanck** [comment]
> The error says:
> 
> ```
>  `require': cannot load such file -- rubocop-project-name
> ```
> 
> The `requires` list in your Rubocop config has:
> 
> ```yaml
>   - rubocop-project_name
> ```
> 
> (note the difference between the names)
> 
> As far as I can tell, neither of these are public gems. Can you share the contents of your `.solargraph.yml` ?

i just changed to post here (and hide project name), is the same in both

**Comment by grncdr** [comment]
> i just changed to post here (and hide project name), is the same in both

Is `rubocop-<project name>` a local gem? (Do you have something like `gem "solargraph-<project name>", path: "..."` in your project Gemfile?). If it is, you should make sure you run solargraph via bundler, because the Gem is not on your global load path.

Again, can you share the `.solargraph.yml`? The `reporters` array in particular should **not** contain `rubocop` if you don't want Solargraph to load Rubocop.
