### ISSUE TITLE
2 Diagnostic errors

### ISSUE THREAD

**Issue by avucic** [castwide/solargraph#647]
Hi

I'm not too familiar with Solargraph but am experiencing a problem with it while I'm trying to setup my Neovim lsp server.
```
solargraph/diagnostics/rubocop.rb:98:in `offense_ending_position': undefined method `code' for nil:NilClass (NoMethodError)\n\n          line = @source.code.lines[start_line]\r\n
```
```
\tfrom /Users/me/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solargraph-0.49.0/lib/solargraph/diagnostics/rubocop.rb:56:in `block in make_array'\n\tfrom /Users/me/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solargraph-0.49.0/lib/solargraph/diagnostics/rubocop.rb:55:in `each'\n\tfrom /Users/me/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solargraph-0.49.0/lib/solargraph/diagnostics/rubocop.rb:55:in `make_array'\n\tfrom /Users/me/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/solargraph-standardrb-1b3ebdf33c00/lib/solargraph-standardrb.rb:16:in `diagnose'\n\tfrom /Users/me/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solargraph-0.49.0/lib/solargraph/library.rb:364:in `block in diagnose'\n\tfrom /Users/me/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solargraph-0.49.0/lib/solargraph/library.rb:363:in `each_pair'\n\tfrom /Users/me/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solargraph-0.49.0/lib/solargraph/library.rb:363:in `diagnose'\n\tfrom /Users/me/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solargraph-0.49.0/lib/solargraph/language_server/host.rb:215:in `diagnose'\n\tfrom /Users/me/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solargraph-0.49.0/lib/solargraph/language_server/host/diagnoser.rb:66:in `tick'\n\tfrom /Users/me/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/solargraph-0.49.0/lib/solargraph/language_server/host/diagnoser.rb:47:in `block in start'\n"
```

```yml
plugins:
  - solargraph-standardrb
reporters:
  - standardrb
```
- robocop
```yml
inherit_gem:
  standard: config/base.yml

```

This setup works fine with Solargraph 0.48

Ruby 3.2.2
Solargraph 0.49
Rubocop (1.48.1, 1.49.0. 1.50)
Let me know if you need more details

**Comment by ocarreterom** [comment]
I'm getting the same error setting up `solargraph-standardrb` in SublimeText.

```
```
