### ISSUE TITLE
Socket error on Mac

### ISSUE THREAD

**Issue by chemzqm** [castwide/solargraph#68]
I use 'socketProvider' from https://github.com/castwide/solargraph-utils same as VSCode.
But when I connect to solargraph, an error is shown:
```
2018-07-08T04:48:49.400 DEBUG (pid:29458) [language-client-client] - Error: Writer recevied error. Reason: connect ECONNREFUSED ::1:55328
    at StreamMessageWriter.AbstractMessageWriter.asError (/Users/chemzqm/vim-dev/coc.nvim/node_modules/vscode-jsonrpc/lib/messageWriter.js:64:20)
    at StreamMessageWriter.AbstractMessageWriter.fireError (/Users/chemzqm/vim-dev/coc.nvim/node_modules/vscode-jsonrpc/lib/messageWriter.js:47:38)
    at Socket.<anonymous> (/Users/chemzqm/vim-dev/coc.nvim/node_modules/vscode-jsonrpc/lib/messageWriter.js:78:68)
    at Socket.emit (events.js:187:15)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
It seems that the server only bind to `localhost:55328` but not `::1:55328`

**Comment by chemzqm** [comment]
It could work when I use
```
 let socket: net.Socket = net.createConnection(socketProvider.port, '127.0.0.1')
```

**Comment by chemzqm** [comment]
The completion could work sometimes, but most times not.

**Comment by castwide** [comment]
Both solargraph and solargraph-utils expect the server to run on localhost (127.0.0.1). It should be possible to add a `--bind` option to the `solargraph socket` command so you can run on a different host.

Can you provide examples of completion requests that don't work? (It might be best to start a different issue for it.)

**Comment by castwide** [comment]
Closed for inactivity. If anyone has ongoing problems with socket errors, please open a new issue.
