### ISSUE TITLE
Ruby 3.4.1 'Solargraph::Parser::Rubyvm::ClassMethods#node_range': undefined method 'first_lineno' for nil (NoMethodError)

### ISSUE THREAD

**Issue by gobijan** [castwide/solargraph#733]
Hi, I just upgraded to Ruby 3.4.1 and it seems that solargraph has a problem?
Could it be due to Rubys new Prism parser? Not sure did not investigate yet.

/Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/parser/rubyvm/class_methods.rb:111:in 'Solargraph::Parser::Rubyvm::ClassMethods#node_range': undefined method 'first_lineno' for nil (NoMethodError)

          st = Position.new(node.first_lineno - 1, node.first_column)
                                ^^^^^^^^^^^^^
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/parser/node_processor/base.rb:53:in 'Solargraph::Parser::NodeProcessor::Base#get_node_location'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/parser/rubyvm/node_processors/resbody_node.rb:12:in 'Solargraph::Parser::Rubyvm::NodeProcessors::ResbodyNode#process'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/parser/node_processor.rb:38:in 'Solargraph::Parser::NodeProcessor.process'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/parser/node_processor/base.rb:46:in 'block in Solargraph::Parser::NodeProcessor::Base#process_children'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/parser/node_processor/base.rb:44:in 'Array#each'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/parser/node_processor/base.rb:44:in 'Solargraph::Parser::NodeProcessor::Base#process_children'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/parser/node_processor/base.rb:34:in 'Solargraph::Parser::NodeProcessor::Base#process'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/parser/node_processor.rb:38:in 'Solargraph::Parser::NodeProcessor.process'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/parser/node_processor/base.rb:46:in 'block in Solargraph::Parser::NodeProcessor::Base#process_children'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/parser/node_processor/base.rb:44:in 'Array#each'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/parser/node_processor/base.rb:44:in 'Solargraph::Parser::NodeProcessor::Base#process_children'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/parser/rubyvm/node_processors/scope_node.rb:9:in 'Solargraph::Parser::Rubyvm::NodeProcessors::ScopeNode#process'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/parser/node_processor.rb:38:in 'Solargraph::Parser::NodeProcessor.process'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/parser/node_processor/base.rb:46:in 'block in Solargraph::Parser::NodeProcessor::Base#process_children'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/parser/node_processor/base.rb:44:in 'Array#each'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/parser/node_processor/base.rb:44:in 'Solargraph::Parser::NodeProcessor::Base#process_children'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/parser/rubyvm/node_processors/def_node.rb:63:in 'Solargraph::Parser::Rubyvm::NodeProcessors::DefNode#process'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/parser/node_processor.rb:38:in 'Solargraph::Parser::NodeProcessor.process'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/parser/node_processor/base.rb:46:in 'block in Solargraph::Parser::NodeProcessor::Base#process_children'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/parser/node_processor/base.rb:44:in 'Array#each'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/parser/node_processor/base.rb:44:in 'Solargraph::Parser::NodeProcessor::Base#process_children'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/parser/node_processor/base.rb:34:in 'Solargraph::Parser::NodeProcessor::Base#process'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/parser/node_processor.rb:38:in 'Solargraph::Parser::NodeProcessor.process'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/parser/node_processor/base.rb:46:in 'block in Solargraph::Parser::NodeProcessor::Base#process_children'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/parser/node_processor/base.rb:44:in 'Array#each'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/parser/node_processor/base.rb:44:in 'Solargraph::Parser::NodeProcessor::Base#process_children'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/parser/rubyvm/node_processors/scope_node.rb:9:in 'Solargraph::Parser::Rubyvm::NodeProcessors::ScopeNode#process'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/parser/node_processor.rb:38:in 'Solargraph::Parser::NodeProcessor.process'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/parser/node_processor/base.rb:46:in 'block in Solargraph::Parser::NodeProcessor::Base#process_children'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/parser/node_processor/base.rb:44:in 'Array#each'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/parser/node_processor/base.rb:44:in 'Solargraph::Parser::NodeProcessor::Base#process_children'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/parser/rubyvm/node_processors/namespace_node.rb:33:in 'Solargraph::Parser::Rubyvm::NodeProcessors::NamespaceNode#process'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/parser/node_processor.rb:38:in 'Solargraph::Parser::NodeProcessor.process'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/parser/rubyvm/class_methods.rb:34:in 'Solargraph::Parser::Rubyvm::ClassMethods#map'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/source_map/mapper.rb:26:in 'Solargraph::SourceMap::Mapper#map'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/source_map/mapper.rb:52:in 'Solargraph::SourceMap::Mapper.map'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/source_map.rb:155:in 'Solargraph::SourceMap.map'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/library.rb:460:in 'block in Solargraph::Library#map!'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/library.rb:459:in 'Array#each'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/library.rb:459:in 'Solargraph::Library#map!'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/api_map.rb:135:in 'Solargraph::ApiMap.load'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/shell.rb:180:in 'block in Solargraph::Shell#scan'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/benchmark-0.4.0/lib/benchmark.rb:304:in 'Benchmark.measure'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/lib/solargraph/shell.rb:179:in 'Solargraph::Shell#scan'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/thor-1.3.2/lib/thor/command.rb:28:in 'Thor::Command#run'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/thor-1.3.2/lib/thor/invocation.rb:127:in 'Thor::Invocation#invoke_command'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/thor-1.3.2/lib/thor.rb:538:in 'Thor.dispatch'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/thor-1.3.2/lib/thor/base.rb:584:in 'Thor::Base::ClassMethods#start'
	from /Users/bijan/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/solargraph-0.50.0/bin/solargraph:5:in '<top (required)>'
	from /Users/bijan/.rbenv/versions/3.4.1/bin/solargraph:25:in 'Kernel#load'
	from /Users/bijan/.rbenv/versions/3.4.1/bin/solargraph:25:in '<main>'

**Comment by omomuki-spirit** [comment]
I have the same issue.
I'm not sure if I got it right, but the following patch addressed it.

ruby34_patch.rb
```ruby
module Solargraph
  module Ruby34Patch
    module RespbodyNode
      def process
        if node.children[1].nil?
          Solargraph::Parser::NodeProcessor.process(node.children[1], region, pins, locals)
        else
          super
        end
      end
    end

    module SendNode
      def process_attribute
        return unless Solargraph::Parser.is_ast_node?(node.children[1])

        node.children[1].children[0..-2].each do |a|
          next unless a.type == :SYM

          opts = {
            location:   get_node_location(node),
            closure:    region.closure,
            comments:   comments_for(node),
            scope:      region.scope || :instance,
            visibility: region.visibility,
            attribute:  true,
          }

          if node.children[0] != :attr_writer
            pins.push Solargraph::Pin::Method.new(name: a.children[0].to_s, **opts)
          end
          next unless node.children[0] != :attr_reader

          pins.push Solargraph::Pin::Method.new(name: "#{a.children[0]}=", **opts)
          pins.last.parameters.push Pin::Parameter.new(name: 'value', decl: :arg, closure: pins.last)
          next unless pins.last.return_type.defined?

          pins.last.docstring.add_tag YARD::Tags::Tag.new(:param, '', pins.last.return_type.to_s.split(', '), 'value')
        end
      end
    end
  end
end

Solargraph::Parser::Rubyvm::NodeProcessors::ResbodyNode.prepend(Solargraph::Ruby34Patch::RespbodyNode)
Solargraph::Parser::Rubyvm::NodeProcessors::SendNode.prepend(Solargraph::Ruby34Patch::SendNode)
```

.solargraph.yml
```yaml
plugins:
  - ./ruby34_patch
```

**Comment by janie314** [comment]
@gobijan @omomuki-spirit  Would you two like to take a look at this PR? I believe it fixes it. https://github.com/castwide/solargraph/pull/735

**Comment by gobijan** [comment]
Just added a comment. Right now I'm on my phone. What you think?

**Comment by janie314** [comment]
@gobijan Apologies, I don't think I'm seeing a comment.

The fix was pretty straightforward-- I just have the method causing issues with Ruby 3.4 return nil when the passed node is nil. If you run the stack trace using [pry](https://rubygems.org/gems/pry)-- the nodes that cause problems are nil.

**Comment by omomuki-spirit** [comment]
@janie314 
Seems to work well, but the sphere of influence may be large.
There is concern that issues that should not be ignored will be ignored.

In my project I have the following two issues

- undefined method error occurs when parsing rescue clause
- attr_accesosr/reader/writer not recognized

So the above patch solved the problem.

**Comment by gobijan** [comment]
> @gobijan Apologies, I don't think I'm seeing a comment.
> 
> The fix was pretty straightforward-- I just have the method causing issues with Ruby 3.4 return nil when the passed node is nil. If you run the stack trace using [pry](https://rubygems.org/gems/pry)-- the nodes that cause problems are nil.

I meant this PR. You could simply go with a guard clause. Just a minor thing.
https://github.com/castwide/solargraph/pull/735
