### ISSUE TITLE
Invalid Byte Sequence

### ISSUE THREAD

**Issue by noelrappin** [castwide/solargraph#84]
see https://github.com/castwide/vscode-solargraph/issues/37

this seems to be a regression in 0.25

**Comment by castwide** [comment]
Gem 0.26.0 has a possible fix. Tested with Unicode on MacOS. More discussion in /vscode-solargraph/#37

**Comment by Sam-Killgallon** [comment]
Unfortunately still having this issue on `v0.28.1`. Works fine if I roll back to `v0.24.1` though.

Stack trace for me is:

```
[Extension Host] invalid byte sequence in UTF-8
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/source_map/mapper.rb:450:in `gsub'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/source_map/mapper.rb:450:in `source_from_parser'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/source_map/mapper.rb:66:in `code_for'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/source_map/mapper.rb:437:in `block in get_method_args'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/source_map/mapper.rb:431:in `each'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/source_map/mapper.rb:431:in `get_method_args'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/source_map/mapper.rb:169:in `block in process'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/source_map/mapper.rb:104:in `each'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/source_map/mapper.rb:104:in `process'

/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:276 [Extension Host] /Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/source_map/mapper.rb:323:in `block in process'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/source_map/mapper.rb:104:in `each'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/source_map/mapper.rb:104:in `process'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/source_map/mapper.rb:323:in `block in process'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/source_map/mapper.rb:104:in `each'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/source_map/mapper.rb:104:in `process'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/source_map/mapper.rb:323:in `block in process'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/source_map/mapper.rb:104:in `each'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/source_map/mapper.rb:104:in `process'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/source_map/mapper.rb:323:in `block in process'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/source_map/mapper.rb:104:in `each'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/source_map/mapper.rb:104:in `process'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/source_map/mapper.rb:323:in `block in process'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/source_map/mapper.rb:104:in `each'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/source_map/mapper.rb:104:in `process'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/source_map/mapper.rb:36:in `map'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/source_map/mapper.rb:53:in `map'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/source_map.rb:119:in `map'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/api_map.rb:78:in `block in catalog'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/api_map.rb:64:in `each'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/api_map.rb:64:in `catalog'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/library.rb:11:in `initialize'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/library.rb:340:in `new'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/library.rb:340:in `load'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/language_server/host.rb:185:in `prepare'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/language_server/message/initialize.rb:8:in `process'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/language_server/host.rb:75:in `start'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/language_server/transport/socket.rb:19:in `process'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/language_server/transport/socket.rb:13:in `block in post_init'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/language_server/transport/data_reader.rb:53:in `parse_message_from_buffer'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/language_server/transport/data_reader.rb:31:in `block in receive'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/language_server/transport/data_reader.rb:26:in `each_char'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/language_server/transport/data_reader.rb:26:in `receive'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/language_server/transport/socket.rb:27:in `receive_data'
/Users/sam/.gem/ruby/2.5.1/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
/Users/sam/.gem/ruby/2.5.1/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/lib/solargraph/shell.rb:25:in `socket'
/Users/sam/.gem/ruby/2.5.1/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/Users/sam/.gem/ruby/2.5.1/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/Users/sam/.gem/ruby/2.5.1/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/Users/sam/.gem/ruby/2.5.1/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
/Users/sam/.gem/ruby/2.5.1/gems/solargraph-0.28.1/bin/solargraph:5:in `<top (required)>'
/usr/local/bin/solargraph:23:in `load'
/usr/local/bin/solargraph:23:in `<main>'
```

**Comment by castwide** [comment]
I'm having trouble reproducing that error, but I suspect it's specific to unrecognized byte sequences in method parameters. Something like these:

```
def foo(ص); end
def foo(bar="ص"); end
```

...although those specific examples didn't cause an error in my tests.

We should be able to fix it, but it would help to have a test case so we can verify the solution.

**Comment by castwide** [comment]
This issue is currently being tracked in #33.
