### ISSUE TITLE
Solargraph 0.28.3 Crash ([Errno::ENOENT] No such file or directory @ rb_sysopen - lib/rack.rb)

### ISSUE THREAD

**Issue by jhstatewide** [castwide/solargraph#99]
Solargraph Version: 0.28.3

Using paired with VS Code 1.28.2 and Ruby Solargraph 0.17.6.

Opening a ruby project with bundler & rack.

Solargraph server crashes with [Errno::ENOENT] No such file or directory @ rb_sysopen - lib/rack.rb.

If I revert back to Solargraph gem version 0.28.2 things work as expected.

.solargraph.yml

```
---
include:
- "app/**/*.rb"
- lib/**/*.rb
exclude:
- spec/**/*
- test/**/*
- vendor/**/*
- node_modules/**/*
- ".bundle/**/*"
domains: []
reporters:
- rubocop
plugins: []
max_files: 5000
```

**Comment by jhstatewide** [comment]
Stacktrace:

```
[Extension Host] No such file or directory @ rb_sysopen - lib/rack.rb
/data/home/josh/worklog2018/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/rack.gemspec:3:in `read'
/data/home/josh/worklog2018/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/rack.gemspec:3:in `block (2 levels) in generate_require_paths'
/usr/local/lib/site_ruby/2.5.0/rubygems/specification.rb:2097:in `initialize'
/data/home/josh/worklog2018/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/rack.gemspec:1:in `new'
/data/home/josh/worklog2018/vendor/bundle/ruby/2.5.0/gems/rack-2.0.5/rack.gemspec:1:in `block in generate_require_paths'
/var/lib/gems/2.5.0/gems/solargraph-0.28.3/lib/solargraph/workspace.rb:149:in `eval'
/var/lib/gems/2.5.0/gems/solargraph-0.28.3/lib/solargraph/workspace.rb:149:in `block in generate_require_paths'
/var/lib/gems/2.5.0/gems/solargraph-0.28.3/lib/solargraph/workspace.rb:145:in `each'
/var/lib/gems/2.5.0/gems/solargraph-0.28.3/lib/solargraph/workspace.rb:145:in `generate_require_paths'
/usr/share/code/reso…rkbench.main.js:282 [Extension Host] /var/lib/gems/2.5.0/gems/solargraph-0.28.3/lib/solargraph/workspace.rb:87:in `require_paths'
/var/lib/gems/2.5.0/gems/solargraph-0.28.3/lib/solargraph/api_map.rb:89:in `catalog'
/var/lib/gems/2.5.0/gems/solargraph-0.28.3/lib/solargraph/library.rb:9:in `initialize'
/var/lib/gems/2.5.0/gems/solargraph-0.28.3/lib/solargraph/library.rb:322:in `new'
/var/lib/gems/2.5.0/gems/solargraph-0.28.3/lib/solargraph/library.rb:322:in `load'
/var/lib/gems/2.5.0/gems/solargraph-0.28.3/lib/solargraph/language_server/host.rb:192:in `prepare'
/var/lib/gems/2.5.0/gems/solargraph-0.28.3/lib/solargraph/language_server/message/initialize.rb:8:in `process'
/var/lib/gems/2.5.0/gems/solargraph-0.28.3/lib/solargraph/language_server/host.rb:75:in `start'
/var/lib/gems/2.5.0/gems/solargraph-0.28.3/lib/solargraph/language_server/transport/socket.rb:19:in `process'
/var/lib/gems/2.5.0/gems/solargraph-0.28.3/lib/solargraph/language_server/transport/socket.rb:13:in `block in post_init'
/var/lib/gems/2.5.0/gems/solargraph-0.28.3/lib/solargraph/language_server/transport/data_reader.rb:53:in `parse_message_from_buffer'
/var/lib/gems/2.5.0/gems/solargraph-0.28.3/lib/solargraph/language_server/transport/data_reader.rb:31:in `block in receive'
/var/lib/gems/2.5.0/gems/solargraph-0.28.3/lib/solargraph/language_server/transport/data_reader.rb:26:in `each_char'
/var/lib/gems/2.5.0/gems/solargraph-0.28.3/lib/solargraph/language_server/transport/data_reader.rb:26:in `receive'
/var/lib/gems/2.5.0/gems/solargraph-0.28.3/lib/solargraph/language_server/transport/socket.rb:27:in `receive_data'
/var/lib/gems/2.5.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
/var/lib/gems/2.5.0/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
/var/lib/gems/2.5.0/gems/solargraph-0.28.3/lib/solargraph/shell.rb:25:in `socket'
/var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
/var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
/var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
/var/lib/gems/2.5.0/gems/solargraph-0.28.3/bin/solargraph:5:in `<top (required)>'
/usr/local/bin/solargraph:23:in `load'
/usr/local/bin/solargraph:23:in `<main>'
```

**Comment by jhstatewide** [comment]
Worked around with https://github.com/castwide/solargraph/pull/100
